### DISCUSSION TITLE
Search Page on Windows 11 with Hugo version v0.134.2 Not Work

### DISCUSSION THREAD

**Discussion by alifgufron** [CaiJimmy/hugo-theme-stack#1060] [General]
Hi,

I deployed my site using the hugo-theme-stack template on my local PC using Windows 11 and hugo version v0.134.2-1c74abd26070b0c12849550c974a9f3f1e7afb06+extended windows/amd64

when im type the keywoard and press enter this search bar not work.

![image](https://github.com/user-attachments/assets/33b6cec8-06b5-4a59-86da-73882c11a98f)

hugo.yaml

```
permalinks:
    post: /:slug/
    
params:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc
```

content/page/search.md
```
+++
title = 'Search'
date = 2024-09-15T19:36:42+07:00
draft = false
layout = 'search'
+++

```

Ah i think problem with syntax on search.md using .toml im try using .yaml like this:

```
---
title: "Search"
slug: "search"
layout: "search"
outputs:
    - html
    - json
menu:
    main:
        weight: -60
        params: 
            icon: search
---
```

The search page its work! Sorry for make noise, cheers 🍻
