### DISCUSSION TITLE
How to active disqus in config.yaml?

### DISCUSSION THREAD

**Discussion by velviagris** [CaiJimmy/hugo-theme-stack#223] [Q&A] [answered]
Hello! After reading the document, I modified my **config.yaml** as below:

```yaml
    comments:
        enabled: true
        provider: disqus

        disqus:
            disqusShortname: https-koonchung-github-io
```

And my blogs' comment area returns an error like this:

![image](https://user-images.githubusercontent.com/23419678/117981783-f5192000-b367-11eb-84c3-1d8d1812d604.png)

I also tried to modified my **config.yaml** like this:

```yaml
    comments:
        enabled: true
        provider: disqus
        disqusShortname: https-koonchung-github-io
```

And my blog's comment feature still doesn't work, please tell me if I have made any mistakes, thank you very much!
