### DISCUSSION TITLE
关于菜单栏的使用，使用第二种方式会找不到页面

### DISCUSSION THREAD

**Discussion by lspiritcoderl** [CaiJimmy/hugo-theme-stack#453] [Q&A]
我的hugo站点有两个主题，有时要切换使用，所以我不想在content文件夹下面写多余的和配置相关的文件，这样另一个主题会将这些文件当成文章发布出来。

于是在定义菜单栏的时候我没有选用推荐的做法，而是选择了第二种方法。

但是选用第二种方法，我发现填写url后，并不能正确找到需要的页面，具体表现如下：

```yaml
menu:
    main:
        - identifier: home
          name: 主页
          url: /
          weight: -100
          params:
              newTab: false
              icon: home


        - identifier: archives
          name: 归档
          url: /archives
          weight: -80
          params:
              newTab: false
              icon: archives
```

当我把配置文件改成这样后，使用`hugo server -D`，archives的菜单栏确实出现了，但是点击后显示404，也就是找不到页面。

我尝试将page文件夹复制到content文件夹下，发现是可以正常使用的，而且url也是`/archives`，不知道为什么直接在yaml中配置没有效果。
