### DISCUSSION TITLE
favicon 指定无效

### DISCUSSION THREAD

**Discussion by spacefan** [CaiJimmy/hugo-theme-stack#463] [Q&A]
配置文件中：

```yaml
params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: FA-space-shuttle-solid
```
`favicon` 参数指定后无法正常显示 `svg`？这个参数如何使用？
