### DISCUSSION TITLE
How to handle sensitive values in `config.yml`?

### DISCUSSION THREAD

**Discussion by donhector** [CaiJimmy/hugo-theme-stack#635] [General]
## Problem

Several comment providers require defining sensitive values (ie credentials, api keys, etc...)  in  your `config.yaml`. If you were to commit  `config.yaml` then you just leaked your secrets to the public.

What's your recommended way to handle this scenario in a secure maner?

### My suggestion

I can think of environment variables as one way to fix the problem.

For example,  in `\layouts\partials\comments\provider\disqusjs.html` the Go template should try to grab the `ApiKey` value [from the environment](https://gohugo.io/functions/getenv/) and if it is not there, then proceed as usual and grab it from `config.yaml` (i.e: keeping backwards compatibility)

This would work very well when building locally or via Github worklfows:

- Locally
  - Have a gitignored `.env` file containing all the secrets, and then source its contents before building.

    _.env_
    ```.env
    HUGO_DISCUSJS_APIKEY=abcd1234
    ```
 
- Github Workflow
  - Configure the sensitive values as Github Secrets, then in the workflow pass them using the `env` keyword.
 
    _.github/workflows/build.yaml_
     ```yaml
     [...]
        - name: Build
          run: hugo --minify
          env:
              HUGO_DISCUSJS_APIKEY: "${{ secrets.HUGO_DISCUSJS_APIKEY }}"
    [...]
    ```
    
    This way no sensitive info would be committed to Git.
    
   How would other folks approach this problem?
