### DISCUSSION TITLE
How to start with Hugo and this theme ?

### DISCUSSION THREAD

**Discussion by liloumuloup** [CaiJimmy/hugo-theme-stack#687] [Q&A] [answered]
Hi ! :wave: 

I'm new to Hugo and kinda lost with the tutorials. I tried to follow [this one](https://docs.stack.jimmycai.com/getting-started#route-2-recommended-use-theme-as-hugo-module) from the theme documentation, but i think i missed something.

* I have a brand new repository
* I copied the content of `exampleSite` from here : https://github.com/CaiJimmy/hugo-theme-stack/tree/master/exampleSite
* I made the commands from these parts of the doc : 
  * https://docs.stack.jimmycai.com/getting-started#route-2-recommended-use-theme-as-hugo-module
  * https://docs.stack.jimmycai.com/getting-started#configuration-and-site-startup
* And when i start hugo, it doesn't work : 
```
git:(main) ✗ hugo server
Error: module "hugo-theme-stack" not found; either add it as a Hugo Module or store it in "/home/liloumuloup/Documents/git/framagit/liloumuloup.space/themes".: module does not exist
```

I tried to create the folder manually but still the same error.

The theme is not supposed to be installed in the `theme` folder ? Maybe i should go to the `git` installation, even if not recommended in the doc ?

I don't know what i missed and i'm not familiar at all with go.
Maybe someone can help ?

Kind regards. :pray: 

---

* OS version : `Ubuntu 22.04.1 LTS`
* Go version : 
```
git:(main) ✗ go version
go version go1.18.1 linux/amd64

```
* Hugo version : 
```
git:(main) ✗ hugo version 
hugo v0.103.0-beebf2afb09a7be36cf12bdec8a99ae9286504e2+extended linux/amd64 BuildDate=2022-09-15T16:23:56Z VendorInfo=snap:0.103.0
```

**Comment by liloumuloup** [comment]
I don't know if it helps, but here is the `config.yaml`. I just added the `module` part at the end of the file : 
```yaml
baseurl: https://example.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Example Site

languages:
    en:
        languageName: English
        title: Example Site
        weight: 1
    zh-cn:
        languageName: 中文
        title: 演示站点
        weight: 2
    ar:
        languageName: عربي
        languagedirection: rtl
        title: موقع تجريبي
        weight: 3

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
        subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/component.html
        waline:
            serverURL:
            lang:
            pageview:
            emoji:
                - https://unpkg.com/@waline/emojis@1.0.1/weibo
            requiredMeta:
                - name
                - email
                - url
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/CaiJimmy/hugo-theme-stack
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com
          params:
              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

module:
  # uncomment line below for temporary local development of module
  # replacements: "github.com/CaiJimmy/hugo-theme-stack/v3 -> ../../hugo-theme-stack"
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false
```

* `go.mod` : 
```
git:(main) cat go.mod 
module <my_git_url>

go 1.19

require github.com/CaiJimmy/hugo-theme-stack/v3 v3.13.0 // indirect
```

* `go.sum` : 
```
git:(main) cat go.sum 
github.com/CaiJimmy/hugo-theme-stack/v3 v3.13.0 h1:59xw34lWmzKrBOxarNBCEN5nR2EA0A4CDCN3yc1vFP0=
github.com/CaiJimmy/hugo-theme-stack/v3 v3.13.0/go.mod h1:IPmCXiIxlFSLFYS0tOmYP6ySLviyeNVSabyvSuaxD+I=
```

Edit : added the go files created when making the go commands.
