### DISCUSSION TITLE
如何在菜单配置外部链接

### DISCUSSION THREAD

**Discussion by MuenYu** [CaiJimmy/hugo-theme-stack#691] [Q&A] [answered]
提问前：
1. 已阅读[文档](https://stack.jimmycai.com/)，但并未在文档中找到答案
2. 在 Issues 和 discussions 中搜索，无相关问题

期望达到的目的：
能够在菜单栏配置跳转其他页面的超链接
![image](https://user-images.githubusercontent.com/22992947/193246528-c51764d8-4fd7-42ed-a3d5-e89f516cf299.png)
例如：配置一个可以直接跳转到 Google 的超链接

**Comment by MuenYu** [comment, marked as answer]
在 `menu.toml` 中填写即可达到如上效果

```toml
[[main]]
identifier = "google"
name = "Google"
url = "https://www.google.com"
[main.params]
icon = "home"
newtab = true
```
