### DISCUSSION TITLE
How to update avatar in the sidebar?

### DISCUSSION THREAD

**Discussion by japananh** [CaiJimmy/hugo-theme-stack#714] [Q&A] [answered]
Hi, where to store the avatar locally? I saw the config of the default avatar in [`config/_default/params.toml`](https://github.com/CaiJimmy/hugo-theme-stack-starter/blob/master/config/_default/params.toml#L21). That default image is found in the folder [`assets/img`](https://github.com/CaiJimmy/hugo-theme-stack/blob/master/assets/img/avatar.png).

```toml
[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png" -> What path should I update here?
```
