### DISCUSSION TITLE
How to start local search

### DISCUSSION THREAD

**Discussion by TigGrak** [CaiJimmy/hugo-theme-stack#728] [Q&A] [answered]
i have created search.md in content and start search function but it did not show anything
![image](https://user-images.githubusercontent.com/85205528/204176959-4ee4eb06-67f5-478d-8943-693b241cb9cc.png)
![image](https://user-images.githubusercontent.com/85205528/204176977-a084236c-c391-4b75-9859-48faaa4a7070.png)
![image](https://user-images.githubusercontent.com/85205528/204177022-d8cd3a8b-7aa4-4bbc-aab0-f90331a56c15.png)
![image](https://user-images.githubusercontent.com/85205528/204177109-4981a52d-4138-4dec-aef3-46285ff14939.png)

**Comment by zhixuan2333** [comment, marked as answer]
It looks like didn't create the search file.
Create a file at `content/page/search/index.md` with the following content.
```yaml
---
title: "Search"
slug: "search"
layout: "search"
outputs:
    - html
    - json
menu:
    main:
        weight: -60
        params: 
            icon: search
---
```
