### DISCUSSION TITLE
无法覆写 `.site-name` 的 `color` 属性

### DISCUSSION THREAD

**Discussion by DreamOneX** [CaiJimmy/hugo-theme-stack#760] [Q&A] [answered]
如题，在 `assets/scss/custom.scss` 中通过
```scss
.site-name {
    color: red !important;
}
```
无法修改 `site-name` 的颜色，貌似是因为优先级低于 `style.scss` 中关于 `a` 标签的修改，即使添加 `!important` 也起不到任何作用，请问如何解决呢

---

* hugo 版本: `hugo v0.100.2-d25cb2943fd94ecf781412aeff9682d5dc62e284+extended linux/amd64 BuildDate=2022-06-08T10:25:57Z VendorInfo=gohugoio`
* hugo-theme-stack 版本 : `v3.16.0`
* 所用浏览器: `Mozilla Firefox 108.0.1 `

**Comment by DreamOneX** [comment, marked as answer]
~~我傻了~~
```scss
.site-name a {
    color: red !important;
}
```
即可
