### DISCUSSION TITLE
How can I add a tags page to the left menu?

### DISCUSSION THREAD

**Discussion by OrangeTeaTime** [CaiJimmy/hugo-theme-stack#772] [Q&A]
I tried to create a new page at contents/page/tags/index.md and then add the menu to the frontmatter. This page shows up on the menu but the content is blank. Here's the frontmatter. There is no other content inside.

```
title: "Tags"
slug: "tags"
url: "/tags"
layout: "single"
menu:
  main:
    weight: -60
    params:
      icon: tag
```
