### DISCUSSION TITLE
How to change the text on the sidebar into Chinese ？

### DISCUSSION THREAD

**Discussion by aiguoli** [CaiJimmy/hugo-theme-stack#898] [Q&A] [answered]
how to change from

![pic1](https://github.com/CaiJimmy/hugo-theme-stack/assets/49404623/432c0c94-d2e6-4d9c-b653-8118a3f0494d)

to

![pic2](https://github.com/CaiJimmy/hugo-theme-stack/assets/49404623/c7cda364-07d9-452c-9fe9-3ed04356ae2c)

After I modified the `/config/_default/menu.toml`, it just added an item below like this

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/49404623/61170e46-3c47-49f4-8011-525f1a668136)

**Comment by Lovirr** [comment, marked as answer]
以"archives"为例
找到 content/page/archives/index.md
```
title: "文章"
date: 2019-05-28
layout: "archives"
slug: "archives"
menu:
    main:
        weight: -70
        params: 
            icon: archives
```
