### DISCUSSION TITLE
How to add Google Analytics?

### DISCUSSION THREAD

**Discussion by HilkopterBob** [CaiJimmy/hugo-theme-stack#899] [Q&A] [answered]
How can i add Google Analytics? Is it bundled in the theme or do i have To-Do IT manually?

**Comment by CaiJimmy** [comment, marked as answer]
Yes, it's bundled in the theme. You need to add the following code to your config file:

https://gohugo.io/templates/internal/#configure-google-analytics

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/5889006/fde92d53-7cb2-45cd-b8fa-59fb9ce4b4d7)

(I assume you are using the latest version of Hugo, which changed the field used to config Google Analytics.)

I see that you are using the starter template. You can past the following code into `config/_default/config.toml` and it should work:

```toml
[services]
  [services.googleAnalytics]
    googleAnalytics = 'G-MEASUREMENT_ID'
```

**Comment by yassinedevop** [comment]
For any 2024 reader, hugo changed `googleAnalytics` to just `ID` :

```toml
[services]
[services.googleAnalytics]
ID = 'G-MEASUREMENT_ID'
```
