### DISCUSSION TITLE
How can I add third-party js library?

### DISCUSSION THREAD

**Discussion by PKUcoldkeyboard** [CaiJimmy/hugo-theme-stack#932] [Q&A] [answered]
I have added the following content to `external.yaml` , but it seems that this library has not been introduced

```yaml
ColorThief:
    - src: https://cdn.bootcdn.net/ajax/libs/color-thief/2.3.0/color-thief.min.js
      integrity: sha256-Ll7WYr987woA8t/B1DXLPSeB1AM5ZqYyMvlNPHzSPVg=
      type: script
```
