### DISCUSSION TITLE
index.html 添加keywords关键词供SEO优化

### DISCUSSION THREAD

**Discussion by L-Super** [CaiJimmy/hugo-theme-stack#933] [Q&A]
请问如果给主页添加keyword关键词，我试图在`config\_default\languages.toml`添加keywords，但是生成的index.html里面并没有keyword关键词
```toml
[zh-cn]
languageName = "简体中文"
title = "xxx"
weight = 1
[zh-cn.params]
description = "xxxx"
keywords = ["C++", "Hugo"]
```
