### DISCUSSION TITLE
Force footer to the bottom of the page?

### DISCUSSION THREAD

**Discussion by anuramat** [CaiJimmy/hugo-theme-stack#958] [Q&A]
Is it possible to force the footer to the bottom even on short/empty pages?

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/45295405/b9956865-e8a4-41e1-83e5-e17e4448633e)

**Comment by CaiJimmy** [comment]
It's not a configurable option. But you can modify the theme's CSS to achieve that. I think the following CSS should work:

```css
.main-container {
    align-items: unset !important;
}

.site-footer {
    margin-top: auto;
}
```
