### ISSUE TITLE
How to custom a multi-language params.sidebar.subtitle ?

### ISSUE THREAD

**Issue by h2dcc** [CaiJimmy/hugo-theme-stack#1018]
### What happened?

Hello, I'm trying to add a language to my website but I noticed there doesn't seem to be a multi-language option in the params.sidebar.subtitle setting.

```
params:
   sidebar:
        emoji: 
        subtitle: sample title
        avatar:
            enabled: true
            local: true
            src: img/avatar.png
```
