### ISSUE TITLE
关于最新版与Waline评论冲突问题

### ISSUE THREAD

**Issue by hengxin007** [CaiJimmy/hugo-theme-stack#1044]
### What happened?

# Waline 评论报错

# 版本与配置

版本：

- hugo：hugo v0.131.0-extended 
- 主题：v3.26.0

配置：`hugo.yaml`

``` yaml
baseurl: https://example.com
languageCode: zh-cn
theme: stack
paginate: 5
title: 你好
copyright: 1

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

# 最后修改时间
frontmatter:
    lastmod: ['lastmod', ':git', ':fileModTime', 'date', 'publishDate']

languages:
    # en:
    #     languageName: English
    #     title: Example Site
    #     weight: 1
    #     params:
    #         description: Example description
    zh-cn:
        languageName: 中文
        title: 123
        weight: 2
        params:
            description: 123
    # ar:
    #     languageName: عربي
    #     languagedirection: rtl
    #     title: موقع تجريبي
    #     weight: 3
    #     params:
    #         description: وصف تجريبي

services:
    # Change it to your Disqus shortname before using
    disqus:
        shortname: "stack"
    # GA Tracking ID
    googleAnalytics:
        id:

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon: /favicon.ico

    footer:
        since: 2024
        customText:

    dateFormat:
        published: 2006-01-02
        lastUpdated: 2006-01-02

    # 首页个人信息
    sidebar:
        emoji: 
        subtitle: hello~
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg
    
    article:
        # BUG 点！
        math: false
        toc: true
        readingTime: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: waline

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:        

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/component.html
        waline:
            serverURL: https://comment.544688.xyz/
            lang: zh-CN
            # 开启统计
            pageview: true
            emoji:
            # 回复时必填的内容
            requiredMeta:
                # - name
                # - email
                # - url
            # 自定义语言设置，参考https://waline.js.org/cookbook/customize/locale.html#locale-%E9%80%89%E9%A1%B9
            locale:
                admin: 站长
                # 评论框的默认的文字
                placeholder: 欢迎留下宝贵的评论！

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: search
            - type: toc


    opengraph:
        twitter:
            # Your Twitter username
            site: 

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://stack.jimmycai.com/config/menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/hengxin007
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com
          params:
              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        # style: average
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

```

# Bug 复现

当 `hugo.yaml` 配置文件中的：`params.article.math` 为 `true` 时，`Waline` 的评论就会显示不出来，一直转圈并且报错：

<img src="https://openai-75050.gzc.vod.tencent-cloud.com/openaiassets_ca70cee75729ace299ea12921b330369_2579861722843624442.png" style="zoom: 67%;" />

<img src="https://openai-75050.gzc.vod.tencent-cloud.com/openaiassets_5fa1b95538938a90fd7ce01928b95539_2579861722843706986.png" style="zoom:67%;" />

如果将 `params.article.math` 改为 `true` 则正常显示，无报错。

### Hugo version

hugo v0.131.0-bfbee17932ff24009008aa94cdd75c0c41f59279+extended windows/amd64 BuildDate=2024-08-02T09:03:48Z VendorInfo=gohugoio

### Theme version

v3.26.0

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

Windows10，Chrome v127.0.6533.89

### Link to Minimal Reproducible Example

https://github.com/hengxin007
