### ISSUE TITLE
github action 执行不成功

### ISSUE THREAD

**Issue by zanderme** [CaiJimmy/hugo-theme-stack#115]
提示错误: Error: module "stack" not found; either add it as a Hugo Module or store it in "/home/runner/work/blog/blog/themes".: module does not exist

**.github/workflows/deploy** action 脚本如下
```yaml
name: Deploy blog file

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        # extended: true

    - name: Build
      run: hugo --minify
```
