### ISSUE TITLE
原生HTML标签的支持

### ISSUE THREAD

**Issue by GideonSenku** [CaiJimmy/hugo-theme-stack#128]
**Describe the bug**
暂时不知道这是个Bug还是一个feature，总是在md中编写原生HTML标签会失效

**Expected behavior**
自定义的标签能够生效

**Screenshots**
<img width="655" alt="截屏2021-01-25 下午4 39 22" src="https://user-images.githubusercontent.com/39037656/105681271-e3804980-5f2b-11eb-8e16-2d5ba05f80c2.png">

**Comment by CaiJimmy** [comment]
需要修改 Hugo Markdown 渲染器的设定。

https://gohugo.io/getting-started/configuration-markup/

```yaml
markup:
  goldmark:
    renderer:
      unsafe: true
```
