### ISSUE TITLE
Avatar not show in posts or pages when local variable is set to false and route is local outsite theme

### ISSUE THREAD

**Issue by julian-alarcon** [CaiJimmy/hugo-theme-stack#134]
**Describe the bug**
When local variable from avatar is set to false the image is not visible from any post or page, only from main site.

**To Reproduce**
1. Set local variable in the avatar and set a valid image in static/img/avatar.png
```yaml
  sidebar:
    subtitle: "Subtitle"
    avatar:
      local: false
      src: "img/avatar.png"
```
2. Open main website, it shows the avatar
3. Open any post or page, main is not available, it's looking for the path `http://localhost:1313/2020/06/09/my-post/img/avatar.png`
And obviously this doesn's exists

**Expected behavior**
Avatar should be available from all the posts, pages, etc

**Screenshots**
![image](https://user-images.githubusercontent.com/30119472/106907553-5f1c8c00-66cc-11eb-9588-6122a76ff612.png)

**Desktop:**
 - OS: Ubuntu Linux 20.04
 - Browser: Chrome/Firefox

Hugo: 0.80.0 extended

**Additional context**
I used gif/png/jpg images, and I got the same result. Code is located here: https://github.com/CaiJimmy/hugo-theme-stack/blob/master/layouts/partials/sidebar/left.html#L9
```html
    <header class="site-info">
        {{ with .Site.Params.sidebar.avatar }}
            <figure class="site-avatar">
                {{ if not .local }}
                    <img src="{{ .src }}" width="300" height="300" class="site-logo" loading="lazy" alt="Avatar">
                {{ else }}
                    {{ $avatar := resources.Get (.src) }}
                    
                    {{ if $avatar }}
                        {{ $avatarResized := $avatar.Resize "300x" }}
                        <img src="{{ $avatarResized.RelPermalink }}" width="{{ $avatarResized.Width }}"
                            height="{{ $avatarResized.Height }}" class="site-logo" loading="lazy" alt="Avatar">
                    {{ else }}
                        {{ errorf "Failed loading avatar from %q" . }}
                    {{ end }}
                {{ end }}
```

**Comment by julian-alarcon** [comment]
After some tests I am using this workaround:
```
  sidebar:
    subtitle: "Sitio web de Julian Alarcon"
    avatar:
      local: false
      src: "../../../../../img/avatar.gif"
```

But, after checking this https://github.com/CaiJimmy/hugo-theme-stack/issues/50 https://github.com/CaiJimmy/hugo-theme-stack/pull/53 I think that my issue is different.

**Comment by CaiJimmy** [comment]
Thanks for reporting 😀

I think it's related to this line:

https://github.com/CaiJimmy/hugo-theme-stack/blob/70cc14fcbe9e229fef7dc2c6a861f1bd6d3c647e/layouts/partials/sidebar/left.html#L12

Instead of `{{ .src }}` it should be `{{ .src | absURL }}`. 

I'll take look at this when I got more time. But you can try the above workaround.

**Comment by CaiJimmy** [comment]
Try:

```
  sidebar:
    subtitle: "Subtitle"
    avatar:
      local: false
      src: "/img/avatar.png"
```

Add a / before `img`
