### ISSUE TITLE
Adding the widget tag-cloud for "categories", on the right content region on Homepage

### ISSUE THREAD

**Issue by eurecomphil** [CaiJimmy/hugo-theme-stack#169]
**Describe the solution you'd like**
It would be perfect (at least for me :-)) to have the same tag-cloud but based on "categories" as well.
On the homepage, it could be placed right under the current tag-cloud, and could be enable/disable via the config.yaml in the `widget` section

**Comment by rmdhnreza** [comment]
You can using tag-cloud css for categories, I've been implements this on my website, btw.
Create `categories.html` in `layouts/partials/widget`
Paste this snippet HTML
<details>
<summary>categories.html</summary>

```
<section class="widget tagCloud">
  <div class="widget-icon">
      {{ partial "helper/icon" "categories" }}
  </div>
  <h2 class="widget-title section-title">{{ T "widget.categoriesCloud.title" }}</h2>

  <div class="tagCloud-tags">
      {{ range first .Site.Params.widgets.categoriesCloud.limit .Site.Taxonomies.categories.ByCount }}
          <a href="{{ .Page.RelPermalink }}" class="font_size_{{ .Count }}">
              {{ .Page.Title }}
          </a>
      {{ end }}
  </div>
</section>
```
</details>

in `config.toml` add this line
<details>
<summary>config.toml</summary>

```
  [params.widgets]
  enabled = [ "search", "archives",  "tag-cloud", "categories" ]

    [params.widgets.archives]
    limit = 5

    [params.widgets.tagCloud]
    limit = 10

    [params.widgets.categoriesCloud]
    limit = 20
```
</details>

in `language.yaml` add this line
<details>
<summary>i18n/en.yaml</summary>

```
widget:
    archives:
        title:
            other: Archives
        more:
            other: More
    tagCloud:
        title:
            other: Tags
    categoriesCloud:
        title:
            other: Categories
```
</details>

Last, Download svg icon, rename to `categories.svg` paste to `assets/icons`

My Website: [rmdhnreza.my.id](https://rmdhnreza.my.id/)
Repo: [https://github.com/rmdhnreza/rmdhnreza.my.id](https://github.com/rmdhnreza/rmdhnreza.my.id)
