### ISSUE TITLE
Blank Home Page

### ISSUE THREAD

**Issue by fathur** [CaiJimmy/hugo-theme-stack#175]
This is a great theme.

After I install it and copy content `example Site` in the content directory, it is almost running well.
The problem is my home page is empty. When I want to view the posts' list, I must click the tag on the right side.
Of course, it already filtered with that tag.

What must I do to view the list of all posts (with paging) on the homepage?

<img width="1785" alt="Screen Shot 2021-03-28 at 22 20 04" src="https://user-images.githubusercontent.com/846678/112757384-d6f39c80-9013-11eb-8341-d2234344febb.png">
<img width="1785" alt="Screen Shot 2021-03-28 at 22 20 09" src="https://user-images.githubusercontent.com/846678/112757397-deb34100-9013-11eb-9d4c-150060b6e351.png">

**Comment by CaiJimmy** [comment]
> The problem is my home page is empty. When I want to view the posts' list, I must click the tag on the right side.

I'll need more information about this. 

The [example site](https://demo.stack.jimmycai.com/) is built using the files from the `exampleSite` folder.

**Comment by fathur** [comment]
This is my config file 

```toml
baseurl = "https://example.com"
languageCode = "en-us"
theme = "hugo-theme-stack"
paginate = 5.0
title = "Fathur"
disqusShortname = ""
DefaultContentLanguage = "id"

[permalinks]
posts = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [
  "posts"
]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2020.0

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = "🍥"
  subtitle = "Celoteh bermanfaat dari profesional developer."

    [params.sidebar.avatar]
    local = true
    src = "img/avatar.png"

  [params.article]
  math = false

    [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "disqus"

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

  [params.widgets]
  enabled = [
    "search",
    "archives",
    "tag-cloud"
  ]

    [params.widgets.archives]
    limit = 5.0

    [params.widgets.tagCloud]
    limit = 10.0

  [params.opengraph]

    [params.opengraph.twitter]
    card = "summary_large_image"

  [params.defaultImage]

    [params.defaultImage.opengraph]
    enabled = false
    local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

  [params.imageProcessing]

    [params.imageProcessing.cover]
    enabled = true

    [params.imageProcessing.content]
    enabled = true

[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = -100.0
  pre = "home"

[related]
includeNewer = true
threshold = 60.0
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100.0

  [[related.indices]]
  name = "categories"
  weight = 200.0

[markup]

  [markup.highlight]
  noClasses = false
```

If you want to see my repository: https://github.com/fathur/blog-hugo
