### ISSUE TITLE
Error calling partial: partial "widget/archive" not found

### ISSUE THREAD

**Issue by kagaya85** [CaiJimmy/hugo-theme-stack#18]
您好，感谢分享的主题

我是初次使用hugo，在编译构建时遇到了找不到”widget/archive“的错误，怀疑时路径配置的问题，但一直没法解决，只好来这里开issue寻求帮助

报错如下
```
ERROR 2020/09/23 22:21:05 render of "taxonomy" failed: execute of template failed: template: _default/list.html:18:7: executing "right-sidebar" at <partialCached "sidebar/right.html" .>: error calling partialCached: "/Users/kagaya/Repos/kagaya85.github.io/themes/hugo-theme-stack/layouts/partials/sidebar/right.html:5:15": execute of template failed: template: partials/sidebar/right.html:5:15: executing "partials/sidebar/right.html" at <partial (printf "widget/%s" $widget) $context>: error calling partial: partial "widget/archive" not found
```
OS: macOS Catalina 10.15.6
Hugo: v0.75.1

部分配置文件如下
```toml
[params]
  mainSections = ["post"]
  featuredImageField = "image"
  [params.widgets]
    enabled = ['archive', 'tag-cloud']
    [params.widgets.archive]
      limit = 5
      ### Archive page relative URL
      path = "archive"       
    [params.widgets.tagCloud]
      limit = 10
  [params.opengraph]
    [params.opengraph.twitter]
      site = "kagaya_85"
      card = "summary_large_image"
  [params.defaultImage]
    [params.defaultImage.article]
      enabled = false
      local = false
      src = ""
    [params.defaultImage.articleList]
      enabled = false
      local = true
      src = ""
    [params.defaultImage.opengraph]
      enabled = false
      local = false
      src = ""
```

期待回复😃
