### ISSUE TITLE
Svg using ![]() rendering without caption and in new line

### ISSUE THREAD

**Issue by njelich** [CaiJimmy/hugo-theme-stack#183]
## Description

When using for example ![Svg Title](Svg link), the SVG renders in a new line. Expected behavior below achieved using a png generated from SVG.

*note:* rendering completely breaks with version 2.3.0, so I think the conditional clause for the svg is not correct.

## To Reproduce

`![The old dragon logo PNG](dragon.png) ![New dragon logo, traced to SVG](dragon.svg)`

## Expected behavior

<img width="967" alt="Screenshot 2021-04-04 at 13 42 51" src="https://user-images.githubusercontent.com/12912633/113508090-5fab9480-954e-11eb-9fd6-f4c83a4d24bc.png">

## Produced result

<img width="946" alt="Screenshot 2021-04-04 at 14 01 37" src="https://user-images.githubusercontent.com/12912633/113508094-62a68500-954e-11eb-9df6-848e1ae42391.png">

## Environment

- **Hugo version** [e.g: 2.2.0]: 
- **Hugo extended?**: Yes

## Content of config.yaml
```yaml
baseurl: example.com
languageCode: en-us
paginate: 5
title: Title

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

enableRobotsTXT: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: img/favicon.ico

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        subtitle: Just a click away
        avatar:
            local: true
            src: img/avatar.jpg

    article:
        math: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          pre: archives

        - identifier: search
          name: Search
          url: search
          weight: -60
          pre: search

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
```

Link to repo: https://gitlab.com/njelich/saelbennoa.gitlab.io
