### ISSUE TITLE
Searching has weird behavior when typing one character keyword

### ISSUE THREAD

**Issue by lynear24** [CaiJimmy/hugo-theme-stack#184]
## Describe the bug
Using a single character as a keyword in the search page creates this weird behavior that nests \<mark\> tags improperly (showing the "rk>" part of \<mark\> as text in the search outputs). It also duplicates matched text the more you type the same letter again.

## Expected behavior
It shouldn't nest the mark tags improperly and it shouldn't duplicate the text in the search output.
I just manually tweaked search.tsx to only accept keywords that are at least 2 chars long (as a temporary fix).
![image](https://user-images.githubusercontent.com/15196698/113513713-9fe63380-959d-11eb-8eb5-0f8097ec10e3.png)
![image](https://user-images.githubusercontent.com/15196698/113514006-d07a9d00-959e-11eb-9aeb-01593a962908.png)

## To Reproduce
Type a complete word and a letter in that same word separated by whitespace. Typing the same letter again and again as another word duplicates the text that matches the search.

## Screenshots
\<mark\> nesting improperly
![image](https://user-images.githubusercontent.com/15196698/113513858-3286d280-959e-11eb-83bf-0f9fe0ad9ef9.png)
![image](https://user-images.githubusercontent.com/15196698/113513823-0d925f80-959e-11eb-9b6a-7f5a9baae2f2.png)

duplicating results
![image](https://user-images.githubusercontent.com/15196698/113513879-429eb200-959e-11eb-9935-2e87e2bb5cde.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.81.0
- **Hugo extended?**: Yes

## Content of config.yaml
```yaml
### Paste the content of the config file here
baseurl: /
languageCode: en-us
theme: stack
paginate: 6
title: Amateur Homie

# Change it to your Disqus shortname before using
disqusShortname: Lynear

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

permalinks:
    post: /post/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: false
    favicon: /favicon.ico

    footer:
        since: 2019
        customText:

    dateFormat:
        published: 02 Jan '06
        lastUpdated: Jan 02 '06 15:04 MST

    sidebar:
        emoji:
        subtitle: Artist(?). Profile picture by Raeny
        avatar:
            local: true
            src: img/layla.png

    article:
        math: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

    widgets:
        enabled:
            - search
            - tag-cloud

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: false

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: /about/
          weight: -90
          pre: user

        - identifier: gallery
          name: Gallery
          url: /gallery/
          weight: -80
          pre: hash

        - identifier: archives
          name: Archives
          url: /archives/
          weight: -70
          pre: archives

        - identifier: search
          name: Search
          url: /search/
          weight: -60
          pre: search

related:
    includeNewer: false
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false

```

## Link to the demo site and/or source repository
[Link to site](https://rinyaa.me)
