### ISSUE TITLE
Search doesn't work: found no layout file for "JSON"

### ISSUE THREAD

**Issue by FuzzyMistborn** [CaiJimmy/hugo-theme-stack#188]
## Describe the bug
Search doesn't work.  I type something in and I get a blank search page

## Expected behavior
Search to work....

## To Reproduce
Just...type something into the search box and hit enter

## Screenshots
Add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/16689090/114254527-f24c9900-997d-11eb-8f68-a136c3d863ff.png)

![image](https://user-images.githubusercontent.com/16689090/114254516-e365e680-997d-11eb-9f27-cb241c58b2c3.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.82.
- **Hugo extended?**: Yes

## Additional context

Here's what pops up in the log:

```
found no layout file for "JSON" for layout "search" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

If it's a UI issue, fill the following information:

## Content of config.yaml
```yaml
baseurl: http://192.168.2.25
languageCode: en-us
theme: stack
paginate: 10
title: 

# Change it to your Disqus shortname before using
#disqusShortname: hugo-theme-stack

# GA Tracking ID
#googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    posts: /:slug/
    pages: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 EST

    sidebar:
        emoji: 
        subtitle:
        avatar:
            local: false
            src: /images/LegalBot_crop.jpg

    article:
        math: false
        license:
            enabled: false
            default: See a typo/mistake or something that could be improved?  Open an issue or PR on Github!

    comments:
        enabled: false
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src: "/images/header.jpg"

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home
        - identifier: about
          name: About
          url: /about
          weight: -90
          pre: user

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false

```

## Link to the demo site and/or source repository
Not up yet.
