### ISSUE TITLE
search does not work on github pages, but normally at localhost

### ISSUE THREAD

**Issue by eastarpen** [CaiJimmy/hugo-theme-stack#192]
**~~Because of some accident， the title is incomplete， here it is~~**

#  ~~search does not work on github pages, but normally at localhost~~

localhost

![lockhost](https://user-images.githubusercontent.com/62453776/114991161-e0ae4880-9ecb-11eb-9893-faf171394c60.jpg)

web

![web1](https://user-images.githubusercontent.com/62453776/114991216-ee63ce00-9ecb-11eb-8454-16b576a97570.jpg)
![web2](https://user-images.githubusercontent.com/62453776/114991224-ef94fb00-9ecb-11eb-9ce6-91ef2581988d.jpg)
![web3](https://user-images.githubusercontent.com/62453776/114991228-f02d9180-9ecb-11eb-8157-640cb8bf7d4a.jpg)

config .yaml

```
baseurl: http://eatarpen.github.io/
languageCode: zh-CN
theme: hugo-theme-stack
paginate: 5
title: Eastarpen の blog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: zh-cn

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 
        subtitle: "welcome"
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 15 

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: 主页
          url: /
          weight: -100
          pre: home



related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false

```

site root dir：
![site_root](https://user-images.githubusercontent.com/62453776/114991616-5adecd00-9ecc-11eb-8984-9b3f6074438d.jpg)

dir`plugins`, file`.gitignore`,`LICENSE` not included in the beginning

after added, no changes for the issue

`update_blog.bat` contents are below:
```
cd /d P:\BLOG\website
rd /Q public
hugo 
cd /d public
git init
git remote add origin git@github.com:eastarpen/eastarpen.github.io.git
git add .
git commit -m 'init'
git push -f --set-upstream origin master
```
