### ISSUE TITLE
Math matrix parsing unexpected behaviour

### ISSUE THREAD

**Issue by Whotakesmyname** [CaiJimmy/hugo-theme-stack#196]
## Describe the bug
A piece of Latex code of a matrix is not correctly parsed.

```
$$
a \times b = A^* b =
\begin{pmatrix}
0 & -z & y\\
z & 0  & -x\\
-y & x & 0
\end{pmatrix}
$$
```

## Expected behavior
It should be rendered as this: (generated by Katex's playground with the same code)
![image](https://user-images.githubusercontent.com/19500528/115581304-785fcc80-a2fa-11eb-99ea-6634ad5601ef.png)

## To Reproduce
Put this piece of code in any post with `math: true`.

## Screenshots
![image](https://user-images.githubusercontent.com/19500528/115581875-fc19b900-a2fa-11eb-9561-9e484b8ad35d.png)

## Environment

- **Hugo version**: hugo v0.82.0-9D960784+extended windows/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio
- **Hugo extended?**: Yes

## Additional context
The problem is caused by the backslashs. Without them, all things are fine. But when backslashes are added, there are some parsing errors I guess. Since Katex processed this code in their website's playground correctly, I think there might be some internal steps wrongly processed the backslashes(`\\`) somewhere and then passed them to Katex. However I haven't found the bug and hope you can help.

## Content of config.yaml
```yaml
baseURL: 'https://blog.darkray.cn'
languageCode: en-us
title: Darkray Blog
paginate: 10
theme: hugo-theme-stack

DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    # favicon is defined in custom header
    favicon:

    footer:
        since: 2016
        customText: '<a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802025962">京公网安备11010802025962号</a>&emsp;<a target="_blank" href="https://beian.miit.gov.cn/">京ICP备17050464号-1</a>'

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🔧
        subtitle: Catch me.
        avatar:
            local: true
            src: img/avatar.jpg

    article:
        math: true
        license:
            enabled: true
            default: Darkray Blog is licensed under CC BY-NC-ND 4.0

    comments:
        enabled: true
        provider: utterances

        utterances:
            repo: Whotakesmyname/darkray-blog
            issueTerm: pathname
            label: comment

        remark42:
            host:
            site:
            locale:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 20

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: img/opengraph.jpg

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: github
          name: Github
          url: https://github.com/Whotakesmyname
          weight: -80
          pre: brand-github

related:
    includeNewer: true
    threshold: 60
    toLower: true
    indices:
        - name: tags
          weight: 150

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
        linenos: true
        guessSyntax: true
```

## Link to the demo site and/or source repository
See the draft in the post *Games 101*, which is not published.
[repo link](https://github.com/Whotakesmyname/darkray-blog)
