### ISSUE TITLE
Related Contents pictures not loading once deployed in GitHub

### ISSUE THREAD

**Issue by VasilyRakche** [CaiJimmy/hugo-theme-stack#198]
## Describe the bug
The picture for Related content are not loading. That only happens once deployed on GitHub, testing it locally with Hugo works ok. 

![image](https://user-images.githubusercontent.com/30003101/115967069-ce1dba00-a530-11eb-9969-f4c92a9b1775.png)

## To Reproduce
I am using example files provided. Building them with **Hugo v0.80.0/extended**
Just replacing the baseurl line with:
```
baseurl: https://vasilyrakche.github.io
```
Build files are written into folder **public** and pushed to [my github repo](https://github.com/VasilyRakche/vasilyrakche.github.io)
You can check how page looks like once deployed [here](https://vasilyrakche.github.io/p/test-chinese/).

## Environment

- **Hugo v0.80.0**
- **Extended**

## Additional context
 - OS: Ubuntu 18.04
 - Browser: Chrome, Mozilla

## Content of config.yaml
```yaml
baseurl: https://vasilyrakche.github.io
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Example Site

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
        subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
```

## Link to the demo site and/or source repository
[Repo with build files](https://github.com/VasilyRakche/vasilyrakche.github.io)
[Deployed website](https://vasilyrakche.github.io/p/test-chinese/)
Source code is used from the **exampleSite** in the theme repo.
