### ISSUE TITLE
关于浮动目录和favicon

### ISSUE THREAD

**Issue by zzzqiii** [CaiJimmy/hugo-theme-stack#203]
您好~最近在使用您设计的这款精美的主题时遇到了两个问题：
1. 关于浮动目录：最近看到您的个人博客有了浮动目录的功能，请问这个hugo主题可以实现吗？我重新下载了这个主题并使用hugo，但是好像并没有出现浮动目录，请问浮动目录要怎么设置呢？
2. 关于网站图标：我想设置一个网站图标，首先在站点目录的static文件夹下新建了favicon文件夹，把网站图标的图片(fire.jpg)放入favicon文件夹中，然后修改了config.yaml的favicon，如下:
```
params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:
        local: true
        src: /favicon/fire.jpg
```
但是最后并没有显示网站图标，请问是哪里出错了呢？

**Comment by zhixuan666** [comment]
1. 浮动目录 #129 
2. https://github.com/CaiJimmy/hugo-theme-stack/blob/master/exampleSite/config.yaml#L21-L26
`favicon/fire.jpg`

**Comment by zzzqiii** [comment]
> ### 浮动目录
> 请看 #129
> 
> ### 网站图标
> https://github.com/CaiJimmy/hugo-theme-stack/blob/325303a7f85bd95f7937325a9495744c56ce3935/exampleSite/config.yaml#L21-L27
> 
> 请更新配置文件
> 
> `/favicon/fire.jpg` -> `favicon/fire.jpg`

感谢回复~
对于网站图标，我更新了配置文件：
```
params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:
        local: true
        src: favicon/fire.jpg
```
但是还是没有出现图标，这是为什么呢？

**Comment by zhixuan666** [comment]
> 感谢回复~
> 对于网站图标，我更新了配置文件：
> 
> ```
> params:
>     mainSections:
>         - post
>     featuredImageField: image
>     rssFullContent: true
>     favicon:
>         local: true
>         src: favicon/fire.jpg
> ```
> 
> 但是还是没有出现图标，这是为什么呢？

https://github.com/CaiJimmy/hugo-theme-stack/blob/325303a7f85bd95f7937325a9495744c56ce3935/exampleSite/config.yaml#L21-L27

```yml
    favicon:
        local: true
        src: favicon/fire.jpg
```

```yml
    favicon: favicon/fire.jpg
```
