### ISSUE TITLE
Widgets not visible when zoomed in 100%

### ISSUE THREAD

**Issue by srinidhibhat45** [CaiJimmy/hugo-theme-stack#207]
## To Reproduce
Indicate the steps to reproduce this bug, if applicable.

## Screenshots
Add screenshots to help explain your problem.

## Environment

- **Hugo version** [e.g: 0.80.0]: 
- **Hugo extended?**: Yes / No

## Additional context

If it's a UI issue, fill the following information:

## Content of config.yaml
```yaml
### Paste the content of the config file here
baseurl: https://srinidhi-blogs.netlify.app
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Srinidhi Bhat - Blogs

enableEmoji: true

# Change it to your Disqus shortname before using
disqusShortname: srinidhibhat

# GA Tracking ID
googleAnalytics: G-4CLC635B4R

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: https://i.ibb.co/4d32BW3/favicon.png
    footer:
        since: 2021
        customText: All Published Content Subject to Copyright.

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 IST

    sidebar:
        emoji: 
        subtitle: In solitude, where we are least alone, we write for we cannot speak...
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        license:
            enabled: true
            default: 2021 Srinidhi Bhat

    comments:
        enabled: true
        provider: disqus
        

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host: https://srinidhi-blogs.netlify.app/
            site: "Srinidhi's Blog"
            locale: en

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 10

        tagCloud:
            limit: 20

    opengraph:
        twitter:
            # Your Twitter username
            site: YourFatGuy

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: img/avatar.png

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home
    

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false

```

## Link to the demo site and/or source repository

https://srinidhi-blogs.netlify.app/

https://github.com/srinidhibhat45/srinidhi-blogs
