### ISSUE TITLE
Search produces 404 when site is in subpath

### ISSUE THREAD

**Issue by sot-tech** [CaiJimmy/hugo-theme-stack#216]
## Describe the bug
Search not working if site deployed to subpath (`http://some.domain/something`), if `relativeURLS=true` and `baseURL` not specified (not applicable 'because of same content in different domains/paths).

## Expected behavior
When deployed to (i.e.) `/test` path and config `relativeURLS` set to `true`, 
`/search/index.json` should be rewritten to `../search/index.json`, but it does not, because [data-json](https://github.com/CaiJimmy/hugo-theme-stack/blob/325303a7f85bd95f7937325a9495744c56ce3935/layouts/page/search.html#L8) attribute [ignored
by hugo postproccessor](https://github.com/gohugoio/hugo/issues/8580#issuecomment-848800234), so search produces 404.

If i forcibly set `data-json="..{{ .Permalink }}"`, same problem with every result's image: they mapped to absolute path segment instead of dot-segment.

## Screenshots
![Screenshot_20210527_211618](https://user-images.githubusercontent.com/41361221/119879335-cab48e80-bf33-11eb-8d64-8552286393bb.jpg)

## Environment

- **Hugo version**: hugo v0.83.1-5AFE0A57+extended
- **Hugo extended?**: Yes

## Additional context
See _Expected behavior_

 - OS: Linux, Windows
 - Browser [e.g. chrome, safari]: chromium 90, firefox 78

## Content of config.yaml
[config.yaml.txt](https://github.com/CaiJimmy/hugo-theme-stack/files/6556120/config.yaml.txt)

## Link to the demo site and/or source repository
-

**Comment by zhixuan666** [comment]
![image](https://user-images.githubusercontent.com/59254886/119943209-af965d00-bfcd-11eb-82c0-5f50e9a71159.png)

```yaml
baseurl: /something
theme: hugo-theme-stack
paginate: 5
title: Example Site

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: ru

permalinks:
    post: /p/:filename/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: false
    favicon: /favicon.ico

    footer:
        since: 2020
        customText:

    dateFormat:
        published: 02.01.2006
        lastUpdated: 02.01.2006

    sidebar:
        subtitle: test test test
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        coverImage:
            enabled: false
        license:
            enabled: true
            default: CC BY-NC 4.0 except otherwise noted

    comments:
        enabled: false
        provider: disqus
        utterances:
            repo:
            issueTerm: pathname
            label:
            theme: preferred-color-scheme

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 15
            path: archives

        tagCloud:
            limit: 100

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true
        
        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: false
        content:
            enabled: false

menu:
    main:
        - identifier: home
          name: На главную
          url: /
          weight: -100
          pre: home        

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false 
```

set `baseurl: /something
