### ISSUE TITLE
Menu icon issue & How to open a new tab in Menu entry ?

### ISSUE THREAD

**Issue by Peckystudios** [CaiJimmy/hugo-theme-stack#218]
Hi 
Thanks for designing a great-looking theme!

I try to add a menu entry to link my store.
I found that the icon I added doesn't change when I click other menus entry
Not sure if the format of SVG is wrong

![](https://i.imgur.com/ec4E6UU.png)

the other question is 

Can I let the menu entry open a new tab?

My page front matter:
![](https://i.imgur.com/RZrWXLS.png)

您好
謝謝你設計了很漂亮的主題！

我想要在主要菜單加入一個連往外部的連結
連結是有成功，但icon卻不會像其他menu一樣變換顏色
不確定是不是svg格式的差異?

另一個問題是有沒有方法可以讓menu開啟的時候在新分頁開啟呢？

## Environment

- **Hugo version** [e.g: 0.80.0]:  v0.83.1+extended darwin/arm64 BuildDate=unknown
- **Hugo extended?**: Yes / No : 

## Additional context

If it's a UI issue, fill the following information:

 - OS: [e.g. iOS]:Mac mini / Big Sur 11.2.3
 - Browser [e.g. chrome, safari] : Chrome

## Content of config.yaml
```yaml
baseurl: https://peckystudios.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Pecky studios

# Change it to your Disqus shortname before using
disqusShortname: peckystudios

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /img/branding/logo_tran-48x48.ico

    footer:
        since: 2021
        customText: Happy with my Blog.

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: ❤️
        subtitle: Everyone is ARTIST!
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home


related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false

```

## Link to the demo site and/or source repository

https://github.com/Peckystudios/PeckyPlayZone
