### ISSUE TITLE
Scrollable TOC and Right Sidebar

### ISSUE THREAD

**Issue by FarrelF** [CaiJimmy/hugo-theme-stack#236]
**Is your feature request related to a problem? Please describe.**
I'm always have a tiny problem when navigating article TOC that using a lot of headings and a problem when navigating right sidebar if I have additional widgets (eg. Categories). TOC and Right Sidebar will navigate down if the page near the end.

**Describe the solution you'd like**
Maybe, the Scrollable TOC and Right Sidebar feature in this theme will be nice, especially for Article that have a lot of Headings or/and have additional Widgets in the Right Sidebar (eg. Categories). But, I don't know how to do that in this theme.

**Describe alternatives you've considered**
No?

**Additional context**
For TOC context, you can see the demo page that using a lot of headings: https://demo.stack.jimmycai.com/p/markdown-syntax-guide/

For Right Sidebar context, you can watch/see the video below:

https://user-images.githubusercontent.com/29566218/123026677-c67e7280-d406-11eb-8017-e9189779cf58.mp4

**Comment by FarrelF** [comment]
I have add this code line below in `custom.scss` for resolve this issue:

```scss
.right-sidebar {
    max-height: 100vh;
    overflow-y: auto;
}

.right-sidebar::-webkit-scrollbar {
    display: none;
}

.widget {
    max-height: 100vh;
    overflow-y: auto;
}

.widget::-webkit-scrollbar {
    display: none;
}
```

But, I still don't know is this good practice or not for resolve this issue.
