### ISSUE TITLE
Image with link

### ISSUE THREAD

**Issue by Peckystudios** [CaiJimmy/hugo-theme-stack#242]
Hello!

How can I make an image with a link?
I think this is a bug or I made some mistakes.

I input this in MD(my blog content)
`[![](https://d.ecimg.tw/items/DGBJBH1900AFJDK/000001_1578976007.jpg)](https://ibestfun.net/2egLl)`

And my page show this
`<img src="https://d.ecimg.tw/items/DGBJBH1900AFJDK/000001_1578976007.jpg" alt="" />`
![image](https://user-images.githubusercontent.com/84195047/123029963-91791c80-d414-11eb-89fd-1f0a49c6a51f.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: hugo v0.83.1+extended darwin/arm64
- **Hugo extended?**: Yes

## Additional context

If it's a UI issue, fill the following information:

 - OS: mac mini
 - Browser chrome

## Content of config.yaml
```yaml
baseurl: https://peckystudios.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Pecky studios

# Change it to your Disqus shortname before using
disqusShortname: peckystudios

# GA Tracking ID
googleAnalytics: G-SMYRRHDDXY


# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /img/branding/logo_tran-48x48.ico

    footer:
        since: 2021
        customText: Happy with my Blog.

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: ❤️
        subtitle: Everyone is ARTIST!
        avatar:
            local: true
            src: img/avatar.png

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home


related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false


```

## Link to the demo site and/or source repository

https://peckystudios.com/p/pokemonss-review-ipanalysis/

**Comment by CaiJimmy** [comment]
I can not reproduce it.

![image](https://user-images.githubusercontent.com/5889006/123065788-c3d44b00-d40f-11eb-95df-a160942697f2.png)
![image](https://user-images.githubusercontent.com/5889006/123065763-c040c400-d40f-11eb-8e19-13f54eb0cda3.png)

**Comment by ciallowo** [comment]
I can't reproduce neither. Maybe set `markup.goldmark.renderer.unsafe` as `true` will solve it, I guess.
```yaml
markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    goldmark:
        renderer:
            unsafe: true # Set this as true
    highlight:
        noClasses: false
```
Or you can just alter a rendering engine like `Blackfriday`, which was Hugo’s default markdown rendering engine. Here is the [Hugo's official docs](https://gohugo.io/getting-started/configuration-markup/#blackfriday).
