### ISSUE TITLE
Dark mode background on versions after v2.3.0 seems broken

### ISSUE THREAD

**Issue by renatoram** [CaiJimmy/hugo-theme-stack#260]
## Describe the bug

Switching from v2.3.0 to a later version makes my site background color light.

I have a site that uses 2.3.0 version, dark mode configured as default, installed as a git submodule in my sources.

If I go in the hugo-theme-stack submodule and "git checkout v2.4.0" suddenly my site's background switches to the light css color. 

The theme selector is on "Dark" and switching it back and forth doesn't seem to do anything.

Tested with both Firefox and Chrome.

Has some configuration changed with 2.4.0?

## Expected behavior
With

```
    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: dark
```
The site should stay dark, unless toggled.

## Steps to reproduce

Site with the theme as submodule. cd into its directory, then 
`git checkout v2.3.0`

Refresh browser a couple of times (or restart hugo serve), it's dark.

`git checkout v2.4.0`

Refresh browser a couple of times (or restart hugo serve), background goes light.
This is consistent and I can switch back and forth.

## Environment

- **Hugo version**: hugo v0.85.0+extended linux/amd64 BuildDate=2021-07-05T14:34:48Z
- **Hugo extended?**: Yes
 - OS: Linux Ubuntu 20.04.2
 - Browser Firefox
 - Version 89.0.2

## Content of config.yaml
```yaml
baseurl: https://renatoram.ch
languageCode: en-us
theme: hugo-theme-stack
paginate: 6
title: A Pinboard For The Mind (Redux)
googleAnalytics: UA-191987824-1

css: "static/css/custom.css"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: favicon.png

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle: Renato Ramonda's random stuff blog
        avatar:
            local: true
            src: summer_2020_150px.jpg

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus
        utterances:
            repo:
            issueTerm: pathname
            label:
            theme: preferred-color-scheme

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: renatoram

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About me
          url: about
          weight: -90
          pre: user

        - identifier: allmylinnks
          name: Where to find me
          url: https://allmylinks.com/renatoram
          weight: -80
          pre: link

        - identifier: archives
          name: Archives
          url: archives
          weight: -30
          pre: archives

        - identifier: GuidaSicurezza
          name: Guida Minima per la Vostra Sicurezza Online
          url: /p/guida-minima-per-la-vostra-sicurezza-online
          weight: -50
          pre: notebook

        - identifier: Scoundrel
          name: A Scoundrel in the Deep
          url: a-scoundrel-in-the-deep
          weight: -40
          pre: diamond

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
```

## Link to the demo site and/or source repository
My site is
https://renatoram.ch

and currently uses v2.2.0 IIRC. I found this bug when trying to update to check out the new toc, and going version by version I saw it seems to break at v2.4.0.
