### ISSUE TITLE
一些Bug

### ISSUE THREAD

**Issue by BacteriumFox** [CaiJimmy/hugo-theme-stack#269]
## 1.并非所有文章都能启用目录功能

我在使用相同分辨率的情况下打开Demo中的文章，但并不是都应用了目录功能

[应用了目录的页面](https://demo.stack.jimmycai.com/p/markdown-syntax-guide/)

[未正确应用目录的页面](https://demo.stack.jimmycai.com/p/emoji-support/)

## 2.希望目录功能增加折叠和支持滚动的功能

在1920*1080的分辨率下，[该页面](https://demo.stack.jimmycai.com/p/markdown-syntax-guide/)的目录部分功能已经无法正确显示，有点过于狭小。

## 3.网页标签无法应用Icon

我的`config.yaml`相关部分的配置如下：

```yaml
    defaultImage:
        opengraph: # 网页图标
            enabled: true
            local: true
            src: img/logo.png
```

我确定我`assets\img`目录下存在有这张图片

![](https://user-images.githubusercontent.com/52241355/126764369-449a3109-be0f-4cb4-91c9-a353d0f691bf.png)

但页面的标签Icon依然无法显示

![](https://user-images.githubusercontent.com/52241355/126764340-ea4d3fc6-29f0-4a79-9df0-e8a0063e902b.png)

## 4.我尝试修改主题背景色，但是没有成功

我修改了`assets\scss`目录下的`variables`文件代码，如图所示，但主界面的背景色依旧没有发生改变。

![](https://user-images.githubusercontent.com/52241355/126764313-6df4b5e4-5a3f-4106-bb24-51f2f7c96c9e.png)

-----

> 十分喜欢作者设计的网页模板，简洁且美观，给作者点个赞b(￣▽￣)d。
>
> 这是我应用作者模板搭建的[网站](https://fungusfox.gitee.io/)，中国外访问可能需要VPN，该网站并非最新的2.6.0版本，大概是2.1.0版本
