### ISSUE TITLE
配置favicon不生效

### ISSUE THREAD

**Issue by Weltolk** [CaiJimmy/hugo-theme-stack#271]
## Describe the bug
配置favicon不生效,试了png和ico格式,都没有效果

## Expected behavior
更改站点图标

## To Reproduce
1.配置site/config.yaml
2.`hugo server`

## Screenshots
相关文件:
![捕获](https://user-images.githubusercontent.com/40228052/126781456-703e2122-8d6a-4e67-95bd-ec785e158753.PNG)

## Environment

- **Hugo version** : 
```
io>hugo version
hugo v0.85.0-724D5DB5 windows/amd64 BuildDate=2021-07-05T10:46:28Z VendorInfo=gohugoio
```
- **Hugo extended?**: No

## Additional context
 - OS: win10 latest
 - Browser: edge 
 - Version: latest

## Content of config.yaml
```yaml
### Paste the content of the config file here
params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: img/ico.ico
```

## Link to the demo site and/or source repository
None
