### ISSUE TITLE
config檔案 TOC ordered設為false後 顯示問題

### ISSUE THREAD

**Issue by hensuu** [CaiJimmy/hugo-theme-stack#283]
## Describe the bug
將根目錄下config.yaml中：
```
markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
```
`ordered`設為`false`後，TOC會同時出現unordered list `<ul>` 以及ordered list `<li>`

## Expected behavior
期望表現為`ordered`設為`false`後，TOC僅出現unordered list `<ul>` 而沒有數字編號

## Screenshots
![image](https://user-images.githubusercontent.com/67720182/127412458-9892426a-dc42-43e1-9b12-430a7abba64b.png)

## Environment

- **Hugo version** : 0.86.0
- **Hugo extended?**: Yes 

## Content of config.yaml
*As Default*
