### ISSUE TITLE
能支持twikoo评论系统吗？

### ISSUE THREAD

**Issue by iwyang** [CaiJimmy/hugo-theme-stack#284]

**Comment by CaiJimmy** [comment]
已经添加了，配置参考 `exampleSite/config.yaml`:

https://github.com/CaiJimmy/hugo-theme-stack/blob/7b51bea912eeb0a1abf6feb0d81479dd202814f5/exampleSite/config.yaml#L90-L94

**Comment by iwyang** [comment]
感觉“发送”按钮有点看不清，![发送按钮](https://cdn.jsdelivr.net/gh/iwyang/pic/202108050953116.jpg)

**Comment by zhixuan666** [comment]
Fix

**Comment by iwyang** [comment]
评论管理是不是有点看不清
![QQ截图20210805203041](https://cdn.jsdelivr.net/gh/iwyang/pic/202108052034245.jpeg)![](https://twikoo.js.org/assets/img/readme-2.5127c8ac.png)

**Comment by zhixuan666** [comment]
我没有 Twikoo 的后端（Vercel 部署一直出错。
如果可以的话你可以自己PR，
或能不能给我部署一个后端。🙏

**Comment by iwyang** [comment]
https://twikoo-lake.vercel.app    刚搭建的，管理密码还未设置，你可以先拿去用，我暂且用waline去的。

**Comment by iwyang** [comment]
> 我没有 Twikoo 的后端（Vercel 部署一直出错。
> 如果可以的话你可以自己PR，
> 或能不能给我部署一个后端。🙏

https://twikoo-lake.vercel.app 刚搭建的，管理密码还未设置，你可以先拿去用，我暂且用waline去的。

**Comment by zhixuan666** [comment]
![image](https://user-images.githubusercontent.com/59254886/128365693-8806bc69-6949-4a09-ad76-371413a6195f.png)
好像没事啊

**Comment by CaiJimmy** [comment]
看了下 Twikoo 的代码，问题应该出在 `.tk-content` 上：

https://github.com/CaiJimmy/hugo-theme-stack/blob/2fd3bde9a40790bf98893b0c5062a2f4c0ac9d8f/layouts/partials/comments/provider/twikoo.html#L20-L24

https://github.com/imaegoo/twikoo/blob/b2e217e22f34ffcb15be4b96f8996e2828c08198/src/view/components/TkAdminComment.vue#L31

https://github.com/imaegoo/twikoo/blob/b2e217e22f34ffcb15be4b96f8996e2828c08198/src/view/components/TkAdmin.vue#L229-L240

有点脏的处理方法：

```css
.tk-admin .tk-content {
    color: #fff!important;
}
```

（我没测试过，不知道有没有用）

**Comment by zhixuan666** [comment]
```css
.twikoo {
    background-color: var(--card-background);
    border-radius: var(--card-border-radius);
    box-shadow: var(--shadow-l1);
    padding: var(--card-padding);
}
:root[data-scheme="dark"] {
    --twikoo-body-text-color-main: rgba(255, 255, 255, 0.9);
    --twikoo-body-text-color: rgba(255, 255, 255, 0.7);
}
.twikoo .el-input-group__prepend,
.twikoo .tk-action-icon,
.twikoo .tk-time,
.twikoo .tk-comments-count {
    color: var(--twikoo-body-text-color);
}
.twikoo .el-input__inner,
.twikoo .el-textarea__inner,
.twikoo .tk-preview-container,
.twikoo .tk-content,
.twikoo .tk-nick,
.twikoo .tk-send {
    color: var(--twikoo-body-text-color-main);
}
.twikoo .el-button{
    color: var(--twikoo-body-text-color)!important;
}
```
这样行不行

https://user-images.githubusercontent.com/59254886/128436109-85ccce61-8c14-4d4d-a04c-9c1906fc461c.mp4
