### ISSUE TITLE
youtube shortcode's class is making videos appear small in size. 

### ISSUE THREAD

**Issue by Sp-cy** [CaiJimmy/hugo-theme-stack#314]
## Describe the bug
Adding videos using {{< youtube >}} shortcode included in the theme makes video appear very small in the single page's body. 

## Expected behavior
Video should be as wide as the container or the padded content area.

## To Reproduce
I thought it was a problem on my side since I added the theme as a module on my main blog repo but then I made a new repo and added theme via git clone and the problem was still there. Just add a youtube video using the shortcode and it will appear tiny. When I renamed the included youtube.html in the shortcodes folder so it would fall back to the included template it started working as before again. 

## Screenshots

Bug...?

![firefox_UxxO8SvsQW](https://user-images.githubusercontent.com/68587155/130049906-c4d184ca-f0d1-4f60-9003-77b56fb3cd5c.png)

Without the youtube.html

![firefox_RNYyCh0IvQ](https://user-images.githubusercontent.com/68587155/130050059-181494c9-bb98-4ab2-9535-a68d154c5418.png)

## Environment

- **Hugo version**:  0.87.0
- **Hugo extended?**: Yes 

If it's a UI issue, fill the following information:

 - OS: Win 10 / Pop!_OS Linux
 - Browser: Firefox
 - Version: v3.1.0

## Content of config.yaml
```yaml
baseurl: https://blog.sp-cy.com/
languageCode: en-us
paginate: 5
title: "Sp-cy"
theme: hugo-theme-stack

# Change it to your Disqus shortname before using
disqusShortname: 

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: es

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /img/favicon.ico
    description: "Blog de Spicy; Gamer, Streamer y productor de contenidos mediaticos de origen Mexicano"   

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🎮
        subtitle: Techno & 1337 Gaming
        avatar:
            local: true
            src: img/spcyredlogo.png

    article:
        math: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: telegram


    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: "@Sp__cy"

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: img/SpicyRedLogo400px.png

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          pre: archives

        - identifier: search
          name: Search
          url: search
          weight: -60
          pre: search

        - identifier: feed
          name: Feed
          url: index.xml
          weight: -50
          pre: rss

        - identifier: live
          name: Live
          url: live
          weight: -40
          pre: device-tv

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false


disableDate: true
disableLatLong: true
enableEmoji: true

defaultContentLanguage: es
languages:
  es:
    weight: 1

  en: 
    weight: 2


# Privacy Settings
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: false
    simple: true
    disableInlineCSS: true
  vimeo:
    disable: false
    enableDNT: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

```

## Link to the demo site and/or source repository
https://blog.sp-cy.com/en/
