### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by itayalush1** [CaiJimmy/hugo-theme-stack#335]
## Describe the bug
I have created a menu item, inside of which I displayed images. But the images do not display - I get that icon that usually pops up when images can not be displayed.

## Expected behavior
I expected the Images to just display properly

## To Reproduce
Maybe try doing the same thing I did - create another menu item and try to display images in it

## Screenshots
![image](https://user-images.githubusercontent.com/66872595/131018257-774b9d3a-1399-4842-ab7b-0e78c87b3db6.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.87.0
- **Hugo extended?**: Yes 

## Additional context
code for the page I that I wanted to display the images in:

```
---
title: "photography"
description: Display test
date: 2021-02-07
slug: photo
menu:
    main: 
        weight: -100
        pre: camera

---

![test](sand.png)
```

If it's a UI issue, fill the following information:

 - OS: ArchCraft Linux
 - Browser: Brave
 - Version 1.28.106

## Content of config.yaml
```yaml
baseurl: https://itayalush.me
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Itay Alush's blog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl, it
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
#        emoji: 🍥
        subtitle: I seriously have no idea
        avatar:
            enabled: true
            local: true
            src: img/mesmol.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        disqusjs:
            shortname: itayalush
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

    widgets:
        enabled:
            - search
#            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: Itayalush

            # Available values: summary, summary_large_image
            card: summary

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false

```

## Link to the demo site and/or source repository
I don't have either of these as of right now, the site is just local until I finish it
