### ISSUE TITLE
Cannot Make Table Item's Texts Center Horizontally

### ISSUE THREAD

**Issue by nullpenguinexception** [CaiJimmy/hugo-theme-stack#339]
## Describe the bug
Normally, it should center text in the table when I write with colon but it doesn't work on my blog.
![image](https://user-images.githubusercontent.com/83981524/131255046-21f095f8-ed6f-4931-b68f-8e34cf22a35a.png)

`| Default Header | Left Align | Right Align | Center Align |`
`| -------------- | :--------- | ----------: | :----------: |`

## Expected behavior
Normally, it should center text in the table when I write with colon. It works correctly with GitLab & GitHub Markdown.

![GitLab Markdown](https://user-images.githubusercontent.com/83981524/131254964-17e6f84c-222a-498c-b801-51fd1641b3a6.png)

## Environment

- **Hugo version**: 0.87.0 
- **Hugo extended?**: Yes

- OS: Windows, Linux, Android

- Browser: Chromium, GeckoView

- Version: Chromium 92, GeckoView 91.

## Content of config.yaml
```yaml
### ### baseurl: https://xxx.xxx.xxx
languageCode: en-us
theme: stack
paginate: 5
title: xxx

# Change it to your Disqus shortname before using
disqusShortname:

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl, it
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: xxx

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle:
        avatar:
            enabled: true
            local: true
            src: xxx

    article:
        math: true
        toc: true
        readingTime: true 
        license:
            enabled: true
            default: xxx
    comments:
        enabled: true
        provider: twikoo

        utterances:
            repo:
            issueTerm: pathname
            label:

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0


        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            dark:
            avatar:
            copyright:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
            placeholder:
            locale:
                admin:
        
        twikoo:
            envId: xxx
            region:
            enable: true
            visitor: true
            path:
            lang: en-US

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

#    opengraph:
#        twitter:
#            # Your Twitter username
#            site:
#
#            # Available values: summary, summary_large_image
#            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home
          params:
              newTab: false
          
        - identifier: xxx
          name: xxx
          url: xxx
          weight:
          pre: link

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false



```
