### ISSUE TITLE
Top banner image didn't show complete

### ISSUE THREAD

**Issue by dev-J-Ariza** [CaiJimmy/hugo-theme-stack#346]
## Describe the bug
Top banner image in the article page didn't show complete.

## Expected behavior
Maybe it should be scaled according to the minimum width or height.

## To Reproduce
url: https://dev-j-ariza.github.io/p/bing%E5%A3%81%E7%BA%B8%E9%A2%84%E8%A7%88%E5%8F%8A%E4%B8%8B%E8%BD%BD/

index.md:  https://github.com/dev-J-Ariza/dev-J-Ariza.github.io/blob/main/content/post/bing-wallpaper-preview/index.md

## Screenshots
<img width="984" alt="截屏2021-09-06 下午3 36 35" src="https://user-images.githubusercontent.com/85870567/132178313-2ea53a0d-bc3f-49ae-ac5a-a6e18f455889.png">

## Environment

- **Hugo version** [e.g: 0.80.0]:  0.88
- **Hugo extended?**: Yes

## Additional context

If it's a UI issue, fill the following information:

 - OS: Mac
 - Browser chrome
 - Version  latest

## Content of config.yaml
```yaml
baseurl: http://dev-J-Ariza.github.io/
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: J-Ariza的点滴

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
        subtitle: 移动开发工程师 & 足球经理
        avatar:
            local: true
            src: img/rick.jpg

    article:
        math: false
        toc: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false

ignoreErrors: ["error-remote-getjson"]

```

## Link to the demo site and/or source repository
[demo site](https://dev-j-ariza.github.io/p/bing%E5%A3%81%E7%BA%B8%E9%A2%84%E8%A7%88%E5%8F%8A%E4%B8%8B%E8%BD%BD/)
