### ISSUE TITLE
（已解决）在本地部署到nginx上，样式不加载

### ISSUE THREAD

**Issue by faxlok** [CaiJimmy/hugo-theme-stack#356]
使用 hugo server -D --disableFastRender 没问题，生成了静态文件之后，部署在本地的nginx上出现了问题。
不过，css文件加载正常
![image](https://user-images.githubusercontent.com/67785456/133727382-ea36f7bd-340d-4c6e-aac0-34060bf233c3.png)

我的配置文件
```
baseurl: http://localhost/
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: Faxlok

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl, it
DefaultContentLanguage: zh-cn

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :fileModTime
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: false
    favicon: /favicon.ico

    footer:
        since: 2021
        customText: “我就是自定义”

    dateFormat:
        published: 2006-01-02 15:04
        lastUpdated: 2006-01-02 15:04

    sidebar:
        emoji: # 头像底部的 Emoji。留空不显示。
        subtitle: おれは天の道行き，総てを司る男になる。
        avatar:
            enabled: true
            local: true
            src: img/android-chrome-384x384.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: 主页
          url: /
          weight: -100
          pre: home
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: true

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 3
        ordered: false
        startLevel: 1
    highlight:
        noClasses: false

```

nginx 配置文件
```
events{}

http{
  server{
    listen 80;

    location / {

      root /Users/saber/faxlok/public;
      index  index.html index.htm;
     
    }
  }
}

```
