### ISSUE TITLE
favicon未生效

### ISSUE THREAD

**Issue by zhj0513** [CaiJimmy/hugo-theme-stack#362]
![image](https://user-images.githubusercontent.com/25121534/134413497-c6bf3632-580b-4ab7-9625-9b4902e219e8.png)

yaml配置文件中： favicon: icons/xxx.svg或者favicon: img/xxx.jpg均为生效

hugo版本：v0.88.1-5BC54738+extended windows/amd64

hugo-theme-stack版本：v3.2.0

chrome浏览器最新版

**Comment by zhixuan2333** [comment]
看看能不能解决 https://github.com/CaiJimmy/hugo-theme-stack/issues/272#issuecomment-891814538

**Comment by QIN2DIM** [comment]
`favicon` 可以指向远程链接，如`YAML Format`：
```yaml
# 站点全局设置
params:
    # 站点的图标
    favicon: https://cdn.pixabay.com/photo/2021/08/23/08/05/triangles-6567058__480.png
```

当然，你也可以指向放置在本地的资源`favicon: img/yourFavicon.jpg`，这个图像文件的路径应是位于站点根目录下的 `./static/img/yourFavicon.jpg`
