### ISSUE TITLE
shortcodes 短码调用异常

### ISSUE THREAD

**Issue by QIN2DIM** [CaiJimmy/hugo-theme-stack#363]
## BUG描述

根据主题文档的提示，可正常引入本地 .mp4 视频以及 YouTube 视频，但**哔哩哔哩**以及**腾讯视频**资源的引用出现异常。
直接访问`<iframe> src` 都可以在网页中直接播放内嵌视频，但是在 Markdown 中通过短码调用引入会出现"仅有体积占用 无视频内容"的情况

## 预期行为

预期行为就如 BUG 描述中那样，既不同源的短码调用都能正常使用。本来想帮助拓展一下主题文档关于 `shortcode`的内容- -写着写着突然怀疑自己了。

一开始还以为是我WRT设置的问题，国内媒体根据IP（版权）阻断了流量，然而可能并不是。我在使用其他工具如`Wolai`，都可正常嵌入(Bilibili等) 视频并播放。

![image](https://user-images.githubusercontent.com/62018067/134458044-a0e4d99c-dfc1-4af4-96ed-7eb268fcc676.png)

### YouTube 短码调用正常
![image](https://user-images.githubusercontent.com/62018067/134455308-779c48f9-07f1-447b-bdb7-c0e4604cd6e9.png)

### Bilibili 短码调用异常，但是API仍然有效
![image](https://user-images.githubusercontent.com/62018067/134455964-f348c5aa-c1ca-47c6-8b47-10161536ebbe.png)

![image](https://user-images.githubusercontent.com/62018067/134456076-7ce2c9af-c567-4b01-bb02-4ec5e0819c61.png)

## Environment
`hugo v0.88.1-5BC54738+extended`

## Content of config.yaml

emmm个人认为其他配置应该不会妨碍这个BUG的出现，毕竟这些东西是相互独立的（吧- -）。如果有什么需要提供的我会补充（不知道只有我有这个问题还是大家都G了）。

```yaml
params:
    #文章页面相关的设置
    article:
        # 在所有文章启用 KaTeX
        math: false
        # 在所有文章启用目录
        toc: true
        # 在所有文章启用阅读时间
        readingTime: true
        # 文章协议设置，显示在页面底部
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0
```

## Link to the demo site and/or source repository
可以在这里查看盛况 -->[跳转](https://blog.echosec.top/p/hugo-shortcode/)
