### ISSUE TITLE
左侧菜单只显示一个、右侧组件只显示标签云

### ISSUE THREAD

**Issue by zhj0513** [CaiJimmy/hugo-theme-stack#368]
大家好，我没有搭建博客经验和前端基础知识，因此小白的问题比较多，不好意思提交太多issue。
请问该项目是否有用于咨询问题的群或者账号？可以互相使用交流，同时老用户可以给新用户解决一些简单问题

当前搭建页面如下：
![image](https://user-images.githubusercontent.com/25121534/134584536-5a80398b-dd2b-47e9-9e03-7d5c73728447.png)

hugo版本：v0.88.1-5BC54738+extended windows/amd64
hugo-theme-stack版本：v3.2.0

问题：
左侧边栏配置了home、about、archive， 但只显示了“Archive”，如上图
右侧边栏的配置了search、archives、tag-cloud，但只显示了一个“标签云”，如上图

另外的问题（文档好像还没相关说明)：
如何给文章增加标签？
如何链接archive的页面？当前点击archive会报404

```
baseurl: https://example.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Gakkiの一般男性

disqusShortname: hugo-theme-stack

googleAnalytics:

DefaultContentLanguage: zh-cn

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
        - my_draft
    featuredImageField: image
    rssFullContent: true
    favicon: /img/github-alt.svg

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 CST

    sidebar:
        emoji: 
        subtitle: 凡事总需研究，才会明白。
        avatar:
            enabled: true
            local: true
            src: img/gakki_avatar.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: coderzhj

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: img/gakki_avatar.jpg

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home
          params:
              newTab: false
    
    main:
        - identifier: about-cn
          name: About
          url: about
          weight: -90
          pre: user
    
    main:
        - identifier: archive
          name: Archive
          url: archive
          weight: -70
          pre: archives
    
related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
```

**Comment by zhixuan2333** [comment]
> 请问该项目是否有用于咨询问题的群或者账号？可以互相使用交流，同时老用户可以给新用户解决一些简单问题

没有，你可以使用discussions

> 左侧边栏（ Home， about，archive）

删除`menu`的设置, `exampleSite/content/page` 拷贝到 `content/page`

https://docs.stack.jimmycai.com/zh/configuration/custom-menu.html#第一种方法-推荐

> 右侧栏
> 如何链接archive的页面？当前点击archive会报404

删除`menu`的设置, `exampleSite/content/page` 拷贝到 `content/page`

添加tag, archive, https://docs.stack.jimmycai.com/zh/writing/supported-front-matter-fields.html


https://docs.stack.jimmycai.com/zh/taxonomy/

**Comment by QIN2DIM** [comment]
这个在写法上是不是有问题

![image](https://user-images.githubusercontent.com/62018067/134602100-a2489fe1-6e00-457c-948c-fae404211c2c.png)

@zhj0513 
 我是这么写的，主要是一个缩进和写法上的问题(你写了多个main)。你可以尝试重新`hugo new site`，用你喜欢的方式再把主题拉去下来，并把`hugo-theme-stack/exampleSite` 文件夹下的内容拷贝覆盖站点根目录（主要是配置文件和 content），根据局部优先原则，写在 Markdown 中的 YAML Font Matter 会优先生效。

```yaml

menu:
    # Note: 确保 identifier 在 menu 中唯一；
    # Note：确保 name 为你希望显示在页面上的内容，比如 Home 就比 home 更加规范美观；
    # Note：确保 pre 为 tag 对应的图标文件名,比如home；
    # Note：为了保证提高文件的可读性，此处的 identifier-array 顺序最好与权重相匹配，也即
    # 最好保持 identifier-array 的顺序与页面中的 tag 顺序一致；
    main:

        # home 主页面
        # identifier 后端系统追踪上下文的唯一标识，与页面显示的内容无关
        - identifier: home
          # name 在页面上显示的内容
          name: Home
          # url 跳转链接
          url: /
          # weight 用于{menu}级别菜单的tag的排序权重，其数值上越“小”，排序越靠“上”。
          weight: -200
          # pre 用于显示{identifier}此项图标
          # 调用~/assets/icons/{pre}.svg作为图标，找不到会报错
          pre: home
          # params 高级diy参数
          params:
              # newTab the link will be open in a new tab
              # newTab: true

        # about 个人简介
        - identifier: about
          name: About
          url: /about
          weight: -195
          pre: user

        # archives 归档
        - identifier: archives
          name: Archives
          url: /archives
          weight: -70
          pre: archives

        # search 内联搜索系统
        - identifier: search
          name: Search
          url: /search
          weight: -60
          pre: search

```
