### ISSUE TITLE
TOC does not render correctly

### ISSUE THREAD

**Issue by wyq977** [CaiJimmy/hugo-theme-stack#374]
## Describe the bug
The TOC is not rendering correctly after I enabled them in config after I updated

## Expected behavior
A TOC just like the Demo

## To Reproduce
https://wyq977.github.io/p/x11-forwarding-on-macos/

## Screenshots

![Screen Shot 2021-09-29 at 4 33 13 PM](https://user-images.githubusercontent.com/27303600/135289995-5f498bba-1d02-43d9-9067-8f5df2a3f2bb.png)

## Environment

- **Hugo version** [0.88.1]: 
- **Hugo extended?**: Yes

## Additional context

If it's a UI issue, fill the following information:

 - OS: macOS
 - Browser: Chrome
 - Version: Version 94.0.4606.61 (Official Build) (arm64)

## Content of config.yaml
```yaml
baseurl: https://wyq977.github.io
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: My Blog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

# Global support for emoji
enableEmoji: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🎯
        subtitle: Just another blog :p
        avatar:
            local: true
            src: img/profile.png

    article:
        math: true
        toc: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus
        utterances:
            repo:
            issueTerm: pathname
            label:
            theme: preferred-color-scheme

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5
            path: archives

        tagCloud:
            limit: 10

    # opengraph:
    #     twitter:
    #         site: wyq977
    #         card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          pre: archives

        - identifier: search
          name: Search
          url: search
          weight: -60
          pre: search

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

# https://gohugo.io/getting-started/configuration-markup/
markup:
    highlight:
        noClasses: false
    goldmark:
        renderer:
            unsafe: true
```

## Link to the demo site and/or source repository

1. https://wyq977.github.io/p/set-up-aria2-and-chrome-working-nicely-together/
2. https://wyq977.github.io/

**Comment by QIN2DIM** [comment]
fine.Please add the following content to your configuration file:
```yaml
markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false


```
