### ISSUE TITLE
请问是否能支持配置不同的RSS地址

### ISSUE THREAD

**Issue by Mantyke** [CaiJimmy/hugo-theme-stack#376]
Hugo自动生成的RSS地址为index.xml
但如果在Page里指定地址为`/index.xml`，以Github Action进行自动部署，Github Action则会报错
![image](https://user-images.githubusercontent.com/89439794/135727929-3a5308f1-df86-472c-94e9-3b01e8e49aee.png)

我使用的Workflow为https://github.com/he-sb/tech/blob/master/.github/workflows/build.yml

如果有别的方法可以解决也请不吝赐教，非常感谢！

**Comment by QIN2DIM** [comment]
Hi~

可以提供更多关于工作流的日志细节吗，我在 [链接指向的 GitHub Actions ](https://github.com/he-sb/tech/blob/master/.github/workflows/build.yml)中看到不到您说的 failed workflow。然后我简单复现了一下环境，拉取了同样的源码和工作流，并没有出现您说的问题0.0

另外，关于 Hugo RSS 的索引策略可以看一下[官方文档的介绍](https://gohugo.io/templates/rss/#lookup-order-for-rss-templates)。

**Comment by QIN2DIM** [comment]
然后是关于您的工作流的写法我有很多疑惑，这个 `build.yml` 是用于远程仓库的吗，为什么要[克隆“本地”代码](https://github.com/he-sb/tech/blob/2cc6a342ef188e9616864de9ebb3cc20aea76e0b/.github/workflows/build.yml#L32)。

最近刚开始上手 workflow，大概看了一下您写的，如果您的情况是 Hugo 源码和 publishDir 渲染输出分别在一个仓库的不同分支下，GitHub Pages 指向 PublishDir 的 /root，完全可以直接 uses [官方提供的脚本](https://gohugo.io/hosting-and-deployment/hosting-on-github/#build-hugo-with-github-action)呀0、0

**Comment by Mantyke** [comment]
> 然后是关于您的工作流的写法我有很多疑惑，这个 `build.yml` 是用于远程仓库的吗，为什么要[克隆“本地”代码](https://github.com/he-sb/tech/blob/2cc6a342ef188e9616864de9ebb3cc20aea76e0b/.github/workflows/build.yml#L32)。
> 
> 最近刚开始上手 workflow，大概看了一下您写的，如果您的情况是 Hugo 源码和 publishDir 渲染输出分别在一个仓库的不同分支下，GitHub Pages 指向 PublishDir 的 /root，完全可以直接 uses [官方提供的脚本](https://gohugo.io/hosting-and-deployment/hosting-on-github/#build-hugo-with-github-action)呀0、0

谢谢回答！我分开来说~
首先我在本地进行的步骤是：新建一个page页面，slug: "index.xml"，这时运行本地预览，可以看到左侧导航栏出现RSS链接，点进去能正常跳转到index.xml
随后进行自动部署，在Bulid的部分报错。

我用的这个工作流来自于https://github.com/reuixiy/hugo-theme-meme/issues/107，是从源代码仓库输出渲染到另一个仓库（这样可以设置源代码仓库为私密），用这个工作流是因为我想在Blog页面上实现自动更新文章最后编辑时间，但如果使用checkout命令，则会导致所有页面的时间都同步更新为自动构建的时间。
实际使用时修改了其中一行，将` git clone --branch=master --quiet https://github.com/$SOURCE_REPO site`修改为`git clone --branch=main --quiet https://$SECRET@github.com/$SOURCE_REPO site。`，用以clone私密仓库。

我公开了我的[源代码仓库](https://github.com/Mantyke/hugo-stack)，您可以在Action中看到具体的报错情况

**Comment by zhixuan2333** [comment]
> 但如果在Page里指定地址为/index.xml，以Github Action进行自动部署，Github Action则会报错

应该是因为主题自动生成rss文件所以出错的。
虽然不是个很好的方法你可以在 `config.yaml` 的 `menu.main`改成这样
```yaml
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home
          params:
            ### For demonstration purpose, the home link will be open in a new tab
            newTab: false

        - identifier: rss
          name: rss
          url: /index.xml
          weight: -10
          pre: home
          params:
            ### For demonstration purpose, the home link will be open in a new tab
            newTab: true

```

> 实现自动更新文章最后编辑时间

虽然跟issue没有什么关系，就是有点在意这个。这是我的workflow，我是可以正常输出的。

```yaml
name: GitHub Page

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.87.0'
          extended: true

      - name: Cache resources
        uses: actions/cache@v2
        with:
          path: |
            resources
          key: ${{ runner.os }}-hugocache-${{ hashFiles('content/**/*') }}
          restore-keys: |
            ${{ runner.os }}-hugocache-

      - name: Build
        run: hugo --minify --gc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          external_repository: zhixuan2333/zhixuan2333.github.io
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: Deploy from ${{ github.repository }}@${{ github.sha }} 🚀

```

**Comment by Mantyke** [comment]
> > 但如果在Page里指定地址为/index.xml，以Github Action进行自动部署，Github Action则会报错
> 
> 应该是因为主题自动生成rss文件所以出错的。 虽然不是个很好的方法你可以在 `config.yaml` 的 `menu.main`改成这样
> 


由衷感谢！已经在Blog里加上了，workflow回头我也试一下

**Comment by zhixuan2333** [comment]
update..
```yml
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
+         fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
```

**Comment by Mantyke** [comment]
> update.. 现在应该可以了
> 
> ```yaml
>       - uses: actions/checkout@v2
>         with:
>           submodules: true  # Fetch Hugo themes (true OR recursive)
> +         fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
> ```

请教一下，具体是什么原因导致的？

**Comment by zhixuan2333** [comment]
`actions/checkout@v2` 默认不会克隆历史信息，加`fetch-depth: 0`就克隆完全的历史信息

**Comment by Mantyke** [comment]
> `actions/checkout@v2` 默认不会克隆历史信息，加`fetch-depth: 0`就克隆完全的历史信息

明白了，谢谢！

**Comment by QIN2DIM** [comment]
> 我用的这个工作流来自于[reuixiy/hugo-theme-meme#107](https://github.com/reuixiy/hugo-theme-meme/issues/107) 是从源代码仓库输出渲染到另一个仓库（目的是设置源代码仓库为私密）


巧了我最近也在研究这个方案https://blog.echosec.top/p/hugo-hugo-deploy/

**Comment by CaiJimmy** [comment]
如果是想把 `index.xml` 改成别的名字，例如 `feed.xml`，可以在 `config.yaml` 添加：

```yaml
outputFormats:
    RSS:
        mediatype: "application/rss"
        baseName: "feed"
```
