### ISSUE TITLE
Add mailto links to social menu

### ISSUE THREAD

**Issue by ttheng3810** [CaiJimmy/hugo-theme-stack#405]
Hello, I am trying to add a ```mailto``` link onto the new social menu feature.

The following is the part of the code in ```config.yaml``` related to the attempt.

```
social:
... # some irrelevant code
    - identifier: email
              name: Email
              url: mailto:johndoe@example.com
              params:
              icon: mail
```

However, the final generated URL corresponding to the icon becomes ```{baseURL}/mailto:johndoe@example.com``` instead of my intended intact ```mailto``` link.

Hoping for a solution here. Thanks!

*Other parts of the website I'm building work well (Hugo version is 0.88.x extended), just that I can't add the* ```mailto``` *link.*
