### ISSUE TITLE
关于页面菜单的中文翻译

### ISSUE THREAD

**Issue by zhangleijuly** [CaiJimmy/hugo-theme-stack#409]
使用中文主题后发现页面菜单的Home、About、Archives和Search比较违和。
请问是否可以通过修改zh-CN.yaml文件实现对页面菜单的汉化（个人尝试了一下没有成功）？
如果可以应该怎样实现？

**Comment by zhixuan2333** [comment]
https://github.com/CaiJimmy/hugo-theme-stack/blob/72a5e956eefa9d84d46504ec65e7f417e295c13e/exampleSite/config.yaml#L171-L180
https://github.com/CaiJimmy/hugo-theme-stack/blob/72a5e956eefa9d84d46504ec65e7f417e295c13e/exampleSite/content/page/about.md?plain=1#L2

如果是在config的话是name，MD里的话是Title

**Comment by zhangleijuly** [comment]
> https://github.com/CaiJimmy/hugo-theme-stack/blob/72a5e956eefa9d84d46504ec65e7f417e295c13e/exampleSite/config.yaml#L171-L180
> 
> 
> https://github.com/CaiJimmy/hugo-theme-stack/blob/72a5e956eefa9d84d46504ec65e7f417e295c13e/exampleSite/content/page/about.md#L2
> 
> 如果是在 config 的话是 name，MD 里的话是 Title

谢谢解答，修改这些字段确实可行，但如果切换回英文就还需要再修改。
想了解一下有没有在翻译文件中增加这些字段的翻译，配置文件中只需要切换语言的方法？

**Comment by zhixuan2333** [comment]
> 想了解一下有没有在翻译文件中增加这些字段的翻译，配置文件中只需要切换语言的方法？

没有。

要是多语言你可以这样

```
languages:
    zh-cn:
        languageName: 中文
        contentDir: content/cn/
        menu:
            main:
                - identifier: home
                  name: 主页
                  url: /
                  weight: -100
                  params:
                      ### For demonstration purpose, the home link will be open in a new tab
                      newTab: false
                      icon: home

    en:
        languageName: english
        weight: 2
        contentDir: content/en/
        languageCode: en
```
