### ISSUE TITLE
Gallery appears to not work

### ISSUE THREAD

**Issue by aaruni96** [CaiJimmy/hugo-theme-stack#415]
## Describe the bug
Gallery does not appear to work. It simply inserts the photos without any gallery styling.

## Expected behavior
Expect to have photos in a gallery style

## To Reproduce
Try to make a gallery in a page.

## Environment

- **Hugo version** [e.g: 0.80.0]:  `hugo v0.90.0-DEV+extended linux/amd64 BuildDate=unknown`
- **Hugo extended?**: Yes / ~~No~~

### Markdown used :
    ![Image 1](cat01.jpg) ![Image 2](cat02.jpg) ![Image 3](cat03.jpg)
    ![Image 4](cat04.jpg) ![Image 5](cat05.jpg) ![Image 6](cat06.jpg)

If it's a UI issue, fill the following information:

 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 94

## Content of config.yaml
```yaml
baseurl: https://lukecypher.xyz
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Luke Cypher Blog

# Change it to your Disqus shortname before using
#disqusShortname: hugo-theme-stack

# GA Tracking ID
#googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: false
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
        subtitle: "In War, Victory. In Peace, Vigilance. In Death, Sacrifice."
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner: 
            admin:  
            repo: 
            clientID: 
            clientSecret: 
        
        cusdis:
            host: 
            id: 

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
#    main:
#        - identifier: home
#          name: Home
#          url: /
#          weight: -100
#          params:
#              ### For demonstration purpose, the home link will be open in a new tab
#              newTab: false
#              icon: home
    
    social:
        - identifier: codeberg
          name: codeberg
          url: https://codeberg.org/LukeCypher
          params:
            icon: brand-codeberg
            
        - identifier: mastodon
          name: Mastodon
          url: https://mastodon.edufor.me/@pavannkumar
          params:
            icon: brand-mastodon

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false

```

## Link to the demo site and/or source repository

https://lukecypher.xyz/
