### ISSUE TITLE
Multi language support 

### ISSUE THREAD

**Issue by IDerr** [CaiJimmy/hugo-theme-stack#421]
Is it possible to have multi language support with this theme for example if we want to write our blog in english and italian/french.... 

Thanks a lot for your work,
Iderr

**Comment by CaiJimmy** [comment]
Currently, there's no button for language switching. You can still create a multi-language site, and add links to the sidebar.

**Comment by cld4h** [comment]
@IDerr 
I added this multilingual switch feature here: https://github.com/cld4h/hugo-theme-stack/commit/9949dd407ec4f8dea2d00275e3ac328747a91fd

[reference](https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/)
Hope this helps.

**Comment by IDerr** [comment]
Thanks a lot ! I'll include it in my blog !

**Comment by jin-li** [comment]
> @IDerr
> I added this multilingual switch feature here: https://github.com/cld4h/hugo-theme-stack/commit/9949dd407ec4f8dea2d00275e3ac328747a91fd
>
>[reference](https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/)
Hope this helps.

@cld4h Thanks for adding this feature! I like it very much! But after applying this in my blog, I can only see the icon but the language selecting button didn't appear (see the figure below):
![Screenshot_select-area_20220219040340](https://user-images.githubusercontent.com/26253144/154794490-f4541712-c6b6-46ad-bce9-4161223a2ae9.png)

I added a few lines in my `config.yaml` file in my site folder:
```yaml
# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
defaultContentLanguage: en
languages:
  en:
    params:
      linkedin: https://linkedin.com/whoever
    title: My blog
    weight: 1
  fr:
    params:
      linkedin: https://linkedin.com/fr/whoever
      navigation:
        help: Aide
    title: Mon blogue
    weight: 2
params:
  navigation:
    help: Help
```
Do you know how I can make the language switch in the sidebar work correctly (show a button to let me select English or French)? Is there any other options that is required in the configuration file? Can you give me some instructions?

Thank you very much!

**Comment by cld4h** [comment]
Oh, just add a `languageName` attribute like this:

```yaml
languages:
  en:
    languageName: "English"
    params:
      linkedin: https://linkedin.com/whoever
    title: My blog
    weight: 1
  fr:
    languageName: "français"
    params:
      linkedin: https://linkedin.com/fr/whoever
      navigation:
        help: Aide
    title: Mon blogue
    weight: 2
```
