### ISSUE TITLE
文章 Toc目录的一些问题

### ISSUE THREAD

**Issue by tanmx** [CaiJimmy/hugo-theme-stack#424]
1. 有些文章的 TOC 不显示如下图
这是我本地md文章的样式
![image](https://user-images.githubusercontent.com/3370587/143394011-4fac9a48-13ca-4490-b287-03c19c2e49d8.png)
这是发布后的样式，没有目录
![image](https://user-images.githubusercontent.com/3370587/143394273-2dcc1feb-d672-4d41-93b9-82348075436d.png)

2. 部分文章的 TOC 生成错误如下图
这是原文大纲样式
![image](https://user-images.githubusercontent.com/3370587/143394611-10b43cb6-e80d-4aca-b264-626196288526.png)
这是发布后的样子
![image](https://user-images.githubusercontent.com/3370587/143394680-1261905e-6753-4598-aed3-77b7af1a19be.png)

- **Hugo version** [0.88.1]: 
- **Hugo extended?**: Yes 

 - OS: [MacOS 12]
 - Browser [Edge]
 - Version [版本 95.0.1020.40 (官方内部版本) (x86_64)]

## Content of config.yaml
```yaml
    article:
        math: false
        toc: toc
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
```
