### ISSUE TITLE
help:搜索功能无法使用

### ISSUE THREAD

**Issue by THU-Pieris** [CaiJimmy/hugo-theme-stack#426]
## Describe the bug
无法搜索到任何东西。自己胡乱修了半天，但是没有头绪。。

## Expected behavior
正常搜索

## To Reproduce
访问我的博客：https://blog.pieris05.com

## Screenshots
\

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.89.4
- **Hugo extended?**:  No

## Additional context

 - OS: [e.g. iOS] macOS 12.0.1
 - Browser [e.g. chrome, safari]: Safari

## Content of config.yaml
```yaml
baseurl: https://blog.pieris05.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Pieris' Blog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🎉
        subtitle: MUG / SynthV / VOCALOID
        avatar:
            enabled: true
            local: true
            src: img/profile.jpg 

    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: utterances

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo: THU-Pieris/blog-comment
            issueTerm: title
            label: comment

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner: 
            admin:  
            repo: 
            clientID: 
            clientSecret: 
        
        cusdis:
            host: 
            id: 

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 15

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: home
    
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/THU-Pieris
          params:
            icon: brand-github

        - identifier: rss
          name: RSS
          url: /index.xml
          params:
            icon: rss
            
        - identifier: keybase
          name: Keybase
          url: https://keybase.io/pieris05
          params:
            icon: key

        - identifier: mainpage
          name: Mainpage
          url: https://pieris05.com
          params:
            icon: world

        - identifier: r-mail
          name: r-mail
          url: https://follow.it/pieris-blog?action=followPub
          params:
            icon: mail

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false

```

## Link to the demo site and/or source repository

Site: https://blog.pieris05.com

Repo: https://github.com/THU-Pieris/blog-hugo
