### ISSUE TITLE
Different styles on Chrome & Edge (social icons)

### ISSUE THREAD

**Issue by azusachino** [CaiJimmy/hugo-theme-stack#435]
## Describe the bug
Different styles on Google Chrome & Microsoft Edge.

## Expected behavior
Same style on both browsers.

## To Reproduce
it's auto deployed, script is [here](https://github.com/azusachino/idealistic-daydreamer/blob/main/.github/workflows/deploy.yml)

## Screenshots
left is chrome, right is edge
![image](https://user-images.githubusercontent.com/18746830/146734179-afbcd9eb-b4e6-4204-87ff-f53ce1b34c65.png)

## Environment

- **Hugo version** : 0.89.0
- **Hugo extended**: Yes
- **theme version**: 3.5.0

## Content of config.yaml
```yaml
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -100
      params:
        icon: home
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/azusachino
      params:
        icon: brand-github
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/azusachino
      params:
        icon: brand-twitter
```

## Link to the demo site and/or source repository
My website [idealistic-daydreamer](https://azusachino.cn)
