### ISSUE TITLE
Social icon does not display

### ISSUE THREAD

**Issue by ichenhe** [CaiJimmy/hugo-theme-stack#443]
## Describe the bug

The social icon (in social menu) does not display. But it does exist in the html.

## Expected behavior
The social icon should display and clickable.

## To Reproduce

Just add social menu:

```yaml
menu:
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/CaiJimmy/hugo-theme-stack
          params:
            icon: brand-github
```

## Screenshots

![image](https://user-images.githubusercontent.com/10266066/147440099-75452c1d-f098-4ecb-99f6-c5a0fadc5d86.png)

## Environment

- **Hugo version** v0.91.0
- **Hugo extended?**: Yes

## Additional context
If it's a UI issue, fill the following information:

 - OS: mac
 - Browser chrome
 - Version 96

## Content of config.yaml
```yaml
baseURL: "https://chenhe.me/"
languageCode: "zh"
title: "晨鹤小站"

theme: "hugo-theme-stack"

outputs:
  home:
    - HTML
    - RSS

permalinks:
  page: /:slug/

menu:
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/ichenhe/
      params:
        icon: brand-github
    - identifier: stackoverflow
      name: StackOverflow
      url: https://stackoverflow.com/users/9150068/
      params:
        icon: brand-stackoverflow

  main:
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
      params:
        icon: folder
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
      params:
        icon: tag
```

---

Param:

```yaml
colorScheme:
  # Display toggle
  toggle: false

article:
  math: true
  toc: true
  readingTime: false

sidebar:
  emoji: 🍥
  subtitle: |
    大学狗; 谷粉。

    🌈 希望每人都是一束光，每人也都可以被照亮。

    🌎 Believe in OPENNESS
  avatar:
    enabled: true
    local: false
    src: https://gravatar.loli.net/avatar/e343865a5581e33479a3d6791891101e?s=150

comments:
  enabled: true
  provider: isso

  isso:
    requireAuthor: true
    gravatar: true

widgets:
  enabled:
    - search
    - tag-cloud
    - archives

  tagCloud:
    limit: 20

  archives:
    limit: 3

footer:
  customText: |
    友情链接：
        <a href="https://lance.moe/" target="_blank">Lance.Moe</a> ·
```

## Link to the demo site and/or source repository

https://chenhe.me/
