### ISSUE TITLE
favicon 指定无效

### ISSUE THREAD

**Issue by spacefan** [CaiJimmy/hugo-theme-stack#462]
配置文件中：

```yaml
params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: FA-space-shuttle-solid
```
`favicon` 参数指定后无法正常显示 `svg`？这个参数如何使用？
