### ISSUE TITLE
如何添加related content模块

### ISSUE THREAD

**Issue by fhb302** [CaiJimmy/hugo-theme-stack#466]
## Describe the bug
您好，很荣幸能使用您的主题，但是在使用过程中浏览官方文档发现您对主题的使用并没有讲的很细致，由于自己并没有太多的前端经验，目前有以下问题，希望您能不吝赐教：
### 无法添加related contents模块
我在复制了您的demo content文件夹替换我原来的content文件夹仍然无法解决。
![无法添加related content模块](https://user-images.githubusercontent.com/10573023/150325748-d68a269c-39b5-4aa8-8d46-fe15e8ddd1db.png)

## Environment

- **Hugo version** [latest]: 
- **Hugo extended?**: Yes 

 - OS: [windows]
 - Browser [edge]
 - Version [latest version]

## Content of config.yaml
```yaml
baseurl: https://example.com
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: 朝闻道

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
    post: /:year/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🎶
        subtitle: 朝闻道，夕可死矣
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: waline

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL: https://blog-api-1jvogda6s-fhb302.vercel.app/
            lang:
            visitor:
            avatar: robohash
            emoji:
                -  https://cdn.jsdelivr.net/gh/sowhereso/waline-blobcatemojis@1.2/blobs
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner: 
            admin:  
            repo: 
            clientID: 
            clientSecret: 
        
        cusdis:
            host: 
            id: 

    widgets:
        enabled:
            - search
            - toc
            - archives
            - categories
            - tag-cloud

        archives:
            limit: 5

        categoriesCloud:
            limit: 20

        tagCloud:
            limit: 20

    opengraph:
        twitter:
            # Your Twitter username
            site: bingoner2

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: true
            src: default_image

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: home

        # - identifier: archives
        #   name: Archives
        #   url: /layouts/partials/widget/archives.html
        #   weight: -100
        #   params:
        #       ### For demonstration purpose, the home link will be open in a new tab
        #       newTab: false
        #       icon: archives

        - identifier: rss
          name: Rss
          url: /index.xml
          weight: -100
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: true
              icon: rss
    
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/fhb302
          params:
            icon: brand-github
            
        - identifier: twitter
          name: Twitter
          url: https://twitter.com
          params:
            icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 6
        ordered: false
        startLevel: 1
    highlight:
            codeFences: true
            guessSyntax: true
            hl_Lines: ""
            lineNoStart: 1
            lineNos: true
            lineNumbersInTable: true
            noClasses: true
            style: dracula
            tabWidth: 4

```
