### ISSUE TITLE
Copy button doesn't work with line number enabled

### ISSUE THREAD

**Issue by leovincentseles** [CaiJimmy/hugo-theme-stack#482]
## Describe the bug
![image](https://user-images.githubusercontent.com/36748589/152298351-4cda33b8-b86a-4b8b-978d-523f7161c199.png)
When I clicked the copy button with lin number enabled, my clipboard will copy the line number like 
 1
 2
 3
 4
 5
 6
 7
 8
 9
10

## Expected behavior
- With the linenumber enabled, I think the copy button should copy the code without line number.

## To Reproduce
Enable the linenumber feature of the highlight blocks.

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.92.1
- **Hugo extended?**: Yes

## Additional context
I also add some css to beautify my highlight block.
```css
/* LineNumbersTable */
.chroma .lnt {
    padding-left: 1.5em !important;
    padding-right: 1.5em !important;
    margin-right: 0 !important;
}

/* code column padding and add left border */
table.lntable td+td {
    border-left: 1px solid black !important;
    padding-left: 20px !important;        
}

/* Radius border for the code block */
div.chroma {
    border-radius: 10px !important;
}

/* Compact style by removing the top and bottom space */
pre.chroma {
    padding-top: 0px !important;
    padding-bottom: 0px !important;
}
```

## Content of config.yaml
```yaml
markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2

    ## See the documentation: https://gohugo.io/content-management/syntax-highlighting/
    highlight:
        codeFences: true
        guessSyntax: true
        hl_Lines: ""
        lineNoStart: 1
        lineNos: true   
        lineNumbersInTable: true
        noClasses: false
        tabWidth: 4
```

## Link to the demo site and/or source repository
- [My personal website](https://leovincentseles.github.io/posts/markdown-syntax-guide/)
