### ISSUE TITLE
Bad code block style after upgrade to 3.8.0

### ISSUE THREAD

**Issue by ichenhe** [CaiJimmy/hugo-theme-stack#489]
## Describe the bug
The code block has an ugly black edge after upgrading to 3.8.0 (light mode) .

I have deleted the `resources` folder.

The problem seems to be caused by not taking `markup.highlight.noClasses=false` into account.

![](https://user-images.githubusercontent.com/10266066/153387412-34dfd0b9-7fe7-4df1-8ec2-9db7798d17fd.png)

## Expected behavior

![](https://user-images.githubusercontent.com/10266066/153387647-731afba1-1aae-4dc3-b82d-0cb0800755b4.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 3.8.0
- **Hugo extended?**: Yes

## Additional context

If it's a UI issue, fill the following information:

 - OS: mac
 - Browser Vivaldi (chromium core)
 - Version 5.0.2497.48

## Content of config.yaml
```yaml
markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2 
  highlight:
    noClasses: false
```

## Link to the demo site and/or source repository

[https://chenhe.me/post/leetcode279-127-126-modeling-with-graph/](https://chenhe.me/post/leetcode279-127-126-modeling-with-graph/)

**Comment by fatFire** [comment]
same question

**Comment by Sunnhild** [comment]
I added this to the custom.scss and it seemed to fix the issue, not sure if it's the best way to do it but it works !
```scss
[data-scheme="light"] {
    .highlight {
        --pre-background-color: #fafafa;
    }
}
```
