### ISSUE TITLE
Copy button is not shown when HTML is rendered

### ISSUE THREAD

**Issue by hiWyatt** [CaiJimmy/hugo-theme-stack#490]
## Describe the bug

In the `config.yaml`,I set `unsafe:true`.After this modification, the copy button will disappear

```yaml
markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
```

## Expected behavior

![](https://s2.loli.net/2022/02/11/orUxF8GZEOSuAHg.png)

![](https://s2.loli.net/2022/02/11/vGP9kMu4iY1mnjt.png)

- When i set `unsafe:false`,the copy button is shown correctly.
- I expect the copy button also appear when i set `unsafe:true`

## To Reproduce

set `unsafe:true` in the `config.yaml`,the copy button is not shown.

## Screenshots

Add screenshots to help explain your problem.

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.92.1
- **Hugo extended?**: Yes

## Additional context

If it's a UI issue, fill the following information:

 - OS: [e.g. iOS]:win11
 - Browser [e.g. chrome, safari]:Microsoft Edge
 - Version [e.g. 22]:98.0.1108.43(64 bit)

## Content of config.yaml

```yaml
markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
        endLevel: 6
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false 
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
```

## Link to the demo site and/or source repository

- [My personal website](https://wangyi.one/vue%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0vue%E5%9F%BA%E7%A1%8003/)
