### ISSUE TITLE
No margin between article links and related content

### ISSUE THREAD

**Issue by Sunnhild** [CaiJimmy/hugo-theme-stack#491]
## Describe the bug
No margin between article links and related content.

## Expected behavior
Margin between article links and related content.

## To Reproduce
Add links to frontmatter of an article with related content.

## Screenshots
Current issue:

![image](https://user-images.githubusercontent.com/29352270/153558514-00e670bd-1e0f-47fe-beed-4ab0ed37dd7a.png)

Expected behavior:

![image](https://user-images.githubusercontent.com/29352270/153558453-6c659037-ede4-4162-b69b-3a2335fe80a7.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.92.1
- **Hugo extended?**: Yes

## Additional context
Fixed by adding this code to the custom.scss, not sure it's the best way to do it.

```scss
.article-list--compact.links {
    margin-bottom: var(--section-separation);
}
```

 - OS: Windows 10
 - Browser: Chromium
 - Version: 98.0.4758.80

## Content of config.yaml
```yaml
related:
    includeNewer: true
    threshold: 60
    toLower: true
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
```

## Link to the demo site and/or source repository
https://www.sunnhild.tk/
