### ISSUE TITLE
Code block indented with four spaces styling in "light" mode

### ISSUE THREAD

**Issue by Sunnhild** [CaiJimmy/hugo-theme-stack#492]
## Describe the bug
Seems like the indented code block theme is "dark" even in "light" mode.

## Expected behavior
The indented code block theme should follow the same rule as any code block in "light" theme.

## To Reproduce
Create a code block by indenting it with four space in "light" mode.

## Screenshots
Current issue:

![image](https://user-images.githubusercontent.com/29352270/153559223-958a28fe-58a9-42c2-b1cd-4f2f1340d10e.png)

Expected behavior:

![image](https://user-images.githubusercontent.com/29352270/153559259-c6861f02-e78a-4425-9320-f377bc021460.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.92.1
- **Hugo extended?**: Yes

## Additional context
Adding this code to custom.scss seemed to fix the issue, again, not sure it's the optimal solution.

```scss
[data-scheme="light"] {
    .article-content pre{
        --pre-background-color: #fafafa;
        --pre-text-color: #272822;
    }
}
```

 - OS: Windows 10
 - Browser: Chromium
 - Version: 98.0.4758.80

## Content of config.yaml
```yaml
### Paste the content of the config file here
```

## Link to the demo site and/or source repository
https://www.sunnhild.tk/
