### ISSUE TITLE
[Documentation] can't use theme as Hugo module

### ISSUE THREAD

**Issue by Anarky** [CaiJimmy/hugo-theme-stack#505]
## Describe the bug
This is the very first time I'm using hugo, so it might be something obvious that I'm missing.
I wanted to use the theme with the "[recommended route](https://docs.stack.jimmycai.com/getting-started#route-2-recommended-use-theme-as-hugo-module)" but I'm getting the error `Error: module "hugo-theme-stack" not found; either add it as a Hugo Module or store it in "/tmp/myblog".: module does not exist`

## Expected behavior
The theme is imported and `hugo server` works.

## To Reproduce
1. create a new website `hugo new site myblog`
2. set it as a module `cd myblog && hugo mod init myblog`
3. add the stack theme `hugo mod get github.com/CaiJimmy/hugo-theme-stack`
4. delete `config.toml`
5. add the requested lines into `config.yaml`
6. start hugo `hugo server`

## Environment

- **Hugo version**: 0.92.2
- **Hugo extended?**: No

## Content of config.yaml
```yaml
module:
  # uncomment line below for temporary local development of module
  # replacements: "github.com/CaiJimmy/hugo-theme-stack -> ../../hugo-theme-stack"
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack
      disable: false
```

**Comment by CaiJimmy** [comment]
Will investigate.

Please use Git submodule meanwhile.

**Comment by CaiJimmy** [comment]
For some unknown reason, Hugo / Go can't detect this theme's latest version:

```bash
@CaiJimmy ➜ /workspaces/hugo-theme-stack-starter (master ✗) $ hugo mod get github.com/CaiJimmy/hugo-theme-stack/v3
go get: module github.com/CaiJimmy/hugo-theme-stack@upgrade found (v2.6.0+incompatible), but does not contain package github.com/CaiJimmy/hugo-theme-stack/v3
go get: module github.com/CaiJimmy/hugo-theme-stack@upgrade found (v2.6.0+incompatible), but does not contain package github.com/CaiJimmy/hugo-theme-stack/v3
@CaiJimmy ➜ /workspaces/hugo-theme-stack-starter (master ✗) $ 
```

I have no clue why this does not work.

**Comment by CaiJimmy** [comment]
Should be fixed now. Run:

```
hugo mod get github.com/CaiJimmy/hugo-theme-stack/v3
```

And use:

```yaml
module:
    imports:
        - path: github.com/CaiJimmy/hugo-theme-stack/v3
```
