### ISSUE TITLE
求助，搜索栏不显示样式、页脚版权信息不显示

### ISSUE THREAD

**Issue by 1368129224** [CaiJimmy/hugo-theme-stack#547]
## Describe the bug
新手刚开始搭建，望大佬有空帮忙看看，非常感谢。另 建议建立群组(QQ/微信/tg)方便用户交流。
1. 搜索栏 不显示样式，无placeholder如图
![image](https://user-images.githubusercontent.com/20501378/157397453-16d45754-9776-42e3-8556-beebdeff9f61.png)
![image](https://user-images.githubusercontent.com/20501378/157397527-33c773de-62d3-4a5a-b80a-3f37182a2b9a.png)
2. 页脚版权链接不显示
![image](https://user-images.githubusercontent.com/20501378/157397957-d608b325-2d6a-4ce2-9171-6fe7f95f5c2a.png)

## Expected behavior
1. 搜索栏样式正常 
![image](https://user-images.githubusercontent.com/20501378/157397937-28e5c547-e152-45c2-8102-cdc92642ec61.png)
2. 页脚版权信息显示正常

## Environment

- **Hugo version** [e.g: 0.80.0]: hugo v0.93.2-643B5AE9+extended linux/amd64 BuildDate=2022-03-04T12:21:49Z VendorInfo=gohugoio
- **Hugo extended?**: Yes

## Additional context
 - OS: windows10
 - Browser: chrome
 - Version: 98.0.4758.102
 
已将`themes\hugo-theme-stack`中的`assets`复制到根目录，将`exampleSite\content`中部分内容复制到`content`中。

## Content of config.yaml
```yaml
baseurl: https://blog.zooter.com.cn
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 10
title: 新泽雪冬

languages:
    cn:
        languageName: 中文
        title: 新泽雪冬
        weight: 2

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage: cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon: 

    footer:
        since: 2022
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
        subtitle: 认清现实，放弃幻想。
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: utterances

        utterances:
            repo: 1368129224/blog
            issueTerm: pathname
            label: github-light

    widgets:
        homepage:
            - type: search
            - type: about
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        github:
            site: 
            
            # Available values: summary, summary_large_image
            card: summary

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: img/bg.jpg

    colorScheme:
        # Display toggle
        toggle: false

        # Available values: auto, light, dark
        default: light

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/1368129224
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://github.com/136812922222
          params:
              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
```

## Link to the demo site and/or source repository

https://github.com/1368129224/Blog
https://blog.zooter.com.cn/
