### ISSUE TITLE
exampleSite的config.yaml文件中中文选项与i18n中的语言文件名称不一致

### ISSUE THREAD

**Issue by cocolight** [CaiJimmy/hugo-theme-stack#551]
现象：使用提供的示例站点配置**exampleSite**的`config.yaml`文件中中文选项与`i18n`中的`ZH-CN`语言文件名称不一致，默认设置为中文后`Dark Mode`会空，
```yaml
languages:
...
    cn:
        languageName: 中文
        title: 演示站点
        weight: 2
...
# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage: en
...
```
测试：将`config.yaml`中的  `cn`改为和语言文件一样可以正常显示
