### ISSUE TITLE
ZH-CN.yaml中缺少categoriesCloud对应翻译

### ISSUE THREAD

**Issue by cocolight** [CaiJimmy/hugo-theme-stack#552]
现象：`ZH-CN.yaml`文件中，`widget`下缺少**categoriesCloud**对应的翻译，切换中文后依旧显示英文
```yaml
widget:
    archives:
        title:
            other: 归档

        more:
            other: 更多

    tagCloud:
        title:
            other: 标签云
```
测试：增加相应的条即可
