### ISSUE TITLE
Sidebar not visible on some posts

### ISSUE THREAD

**Issue by Jontes-Tech** [CaiJimmy/hugo-theme-stack#553]
## Describe the bug
Sidebar not visible on some posts.

## Expected behavior
The sidebar to be visible on all posts

## To Reproduce
Clone my repo (https://github.com/Jontes-Tech/blog) and look in the post about Hugo or the one about Arch.

## Screenshots
Bug: ![Bug](https://user-images.githubusercontent.com/84264740/158007763-7f228321-58d6-498c-bde3-15478e46261d.png)
ExpectedBehavior: ![ExpectedBehavior](https://user-images.githubusercontent.com/84264740/158007764-71741c5d-d32a-4d17-96fe-661b1c6ffd79.png)

## Environment

- **Hugo version** v0.93.2
- **Hugo extended?**: Yes

## Additional context
Not really

If it's a UI issue, fill the following information:

 - OS: All
 - Browser Firefox and Chrome tested, I'd suspect most browsers.
 - Version Most

## Content of config.yaml
```yaml
baseurl: /
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Jontes Blog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
#googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText: Licensed under CC BY-NC-SA 4.0

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 👋
        subtitle: Hi, I'm Jonte! A barely 13 year old tech geek.
        avatar:
            enabled: true
            local: false
            src: /img/apple-touch-icon.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

    widgets:
        enabled:
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: true
              icon: home

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/Jontes-Tech
          params:
              icon: brand-github

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

```

## Link to the demo site and/or source repository
https://blog.jontes.page
https://github.com/Jontes-Tech/blog
