### ISSUE TITLE
vssue 依赖 Vue 2.x ，但 CDN 链接没指定 Vue 版本导致 404 错误

### ISSUE THREAD

**Issue by nnnewb** [CaiJimmy/hugo-theme-stack#561]
## Describe the bug

vssue 依赖 Vue 2.x 版本，但 CDN 没指定版本导致拿不到 `vue.runtime.min.js`

https://github.com/CaiJimmy/hugo-theme-stack/blob/7d1713d40729fa6984ff92c6fd9e41c864915ff2/layouts/partials/comments/provider/vssue.html#L6

实测改为

```html
<script src="https://unpkg.com/vue@2.6.14/dist/vue.runtime.min.js"></script>
```

可以解决这一问题。

建议把 vssue 和 vue 都锁定版本，一是防止现在这种依赖不匹配的问题，二是防范供应链攻击。参见近期的 [node-ipc 供应链攻击](https://github.com/RIAEvangelist/node-ipc/issues/233)。

## Expected behavior

不应该出现 404

## To Reproduce

直接点 `vssue.html` 里的这个 script 链接就会发现404了。

## Screenshots

![image](https://user-images.githubusercontent.com/16402753/158920128-bd6cb590-ab6b-487b-9592-48bf36a772c4.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: hugo v0.93.0-07469082+extended windows/amd64 BuildDate=2022-02-28T08:30:42Z VendorInfo=gohugoio
- **Hugo extended?**: Yes

## Additional context

 - OS: Windows 10
 - Browser Edge (Chromium 内核)
 - Version Edge 版本 99.0.1150.39 (正式版本) (64 位)

## Content of config.yaml
```yaml
vssue:
    platform: github
    owner: nnnewb
    repo: blog
    clientId: **removed**
    clientSecret: **removed**
    autoCreateIssue: true
```
