### ISSUE TITLE
Images in folder are not fetched if file is not called index.md

### ISSUE THREAD

**Issue by dag7dev** [CaiJimmy/hugo-theme-stack#570]
## Describe the bug
When we want to create an image gallery, we need to make a folder and place our blog post and our images.

If post is not named as ´index.md´ it won´t render any image.

## Expected behavior
I should be able to name my file as I prefer.

## To Reproduce
1. go to content post
2. create a folder (named as you want)
3. create a blog post md file in this folder named as you want but index.md, then place a test image
4. try to render the image in the post md file. You won´t succeed.

## Environment
- **Hugo version**: hugo v0.92.2 
- **Hugo extended?**: Yes

## Additional context
If it's a UI issue, fill the following information:

 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari]: Firefox, Brave
 - Version [e.g. 22] latest available

## Content of config.yaml
```yaml
baseurl: ---redacted---
languageCode: en-us
theme: hugo-theme-stack
paginate: 10
title: ---redacted---

enableEmoji: true

# Change it to your Disqus shortname before using
disqusShortname: ---redacted---

# GA Tracking IDl
googleAnalytics: ---redacted---

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl, it
DefaultContentLanguage: en

permalinks:
    post: /:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 CEST

    sidebar:
        emoji: 
        subtitle: ---redacted---
        avatar:
            enabled: false
            local: true
            src: img/avatar.png

    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: ---redacted---

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:

    social:
        - identifier: ...
          name: ...
          url: ...
          params:
              icon: ...

    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              icon: home
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
```
