### ISSUE TITLE
Disable imageProcessing doesn't work on image of categories

### ISSUE THREAD

**Issue by wxjv99** [CaiJimmy/hugo-theme-stack#574]
## Expected behavior
When I set **imageProcessing.cover.enabled = false**, The unprocessed image should be used, like this

![image](https://user-images.githubusercontent.com/48554906/160899364-2edd7dab-03e1-43c4-8849-3c532974339e.png)

## Screenshots

In fact uses a processed image

![image](https://user-images.githubusercontent.com/48554906/160900739-9fd544b0-8078-43c8-aae5-e54f08be4ec9.png)

## Environment

- **Hugo version**: **0.96**
- **Hugo extended?**: **Yes**

## Content of config.yaml
```yaml
params:

  # ...

  imageProcessing:
    cover:
      enabled: false
```
