### ISSUE TITLE
评论插件Twikoo在dark mode下表情选择框是白色

### ISSUE THREAD

**Issue by Weltolk** [CaiJimmy/hugo-theme-stack#583]
## Describe the bug
评论插件Twikoo在dark mode下表情选择框是白色

## Expected behavior
适配dark mode

## To Reproduce
按照官方文档安装本主题和该评论插件,然后切换主题到dark mode

## Screenshots
![image](https://user-images.githubusercontent.com/40228052/162895304-dd26bbbe-9b95-4b78-b868-49c175d813ae.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: [hugo_extended_0.96.0_Windows-64bit.zip](https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_extended_0.96.0_Windows-64bit.zip)
- **Hugo extended?**: Yes

## Additional context

- **[hugo-theme-stack](https://github.com/CaiJimmy/hugo-theme-stack) version** [e.g: 0.80.0]: v3.11.0
- **[twikoo](https://github.com/imaegoo/twikoo) version** [e.g: 0.80.0]: 1.5.3

If it's a UI issue, fill the following information:

 - OS: 
```
Edition	Windows 10 Pro
Version	21H2
Installed on	‎2022.‎04.‎10
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0
```
 - Browser: Microsoft Edge
 - Version: Version 100.0.1185.39 (Official build) (64-bit)

## Content of config.yaml
```yaml
### Paste the content of the config file here

baseurl: https://xxxx.github.io/
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: xxxx

languages:
    en:
        languageName: English
        title: xxxx
        weight: 1
    zh-cn:
        languageName: 中文
        title: xxxx
        weight: 2

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: ar, ca, de, el, en, es, fr, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /img/favicon.png

    footer:
        since: 2022
        customText: xxxxxxxx

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🍥
        subtitle: xxxxxxxx
        avatar:
            enabled: true
            local: true
            src: img/src.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: twikoo

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId: https://twikoo-xxxx-vercexxx.vercel.app/
            region:
            path:
            lang: en-US

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []
    
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/xxxx
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com
          params:
              icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
```

## Link to the demo site and/or source repository
nothing

**Comment by rmdhnreza** [comment]
I'm not using Twikoo, but try to overwrite Twikoo CSS like this in `custom.css`
```css
.OwO .OwO-body {
    background-color: var(--body-background) !important;
    color: var(--body-text-color) !important;
}
```
