### ISSUE TITLE
i18n translation key renaming

### ISSUE THREAD

**Issue by CaiJimmy** [CaiJimmy/hugo-theme-stack#63]
Related with #62, I thought about renaming some i18n translation keys.

For example, `searchPlaceholder` to `search.placeholder`, **grouping translations by context**.

The result would be something like:

```yaml

toggleMenu:
    other: Toggle Menu

article:
    relatedContents:
        other: Related contents
    lastUpdatedOn:
        other: Last updated on

notFound:
    title:
        other: Not Found
    subtitle:
        other: This page does not exist.

widget:
    archives:
        title:
            other: Archives
        more:
            other: More
    tagCloud:
        title:
            other: Tags

search:
    title:
        other: Search
    placeholder:
        other: Type something...
    resultTitle:
        other: '#PAGES_COUNT pages (#TIME_SECONDS seconds)'

footer:
    builtWith:
        other: 'Built with {{ .Generator }}'
    designedBy:
        other: 'Theme {{ .Theme }} designed by {{ .DesignedBy }}'

```
