### ISSUE TITLE
[Bug]: Search doesn't respect disablePathToLower option and returns case sensitive URLs

### ISSUE THREAD

**Issue by rudelm** [CaiJimmy/hugo-theme-stack#778]
### What happened?

I'm not sure when this happened, but recently when I searched on my blog, I was able to open the search results. This stopped or never worked, I'm not sure about it.

Example:
Search for mqtt: https://centurio.net/page/search/?keyword=mqtt
Search results are case sensitive, clicking on one returns a 404

If I go back to the found pages from the frontpage, I'll see correct case insensitive links which are all lower case:
https://centurio.net/2019/12/16/configure-mosquitto-mqtt-broker-user-authentication-in-docker-running-on-synology-nas/

That corresponds to the folder structure on the server, which is all lower case.

my config.yaml:
```yaml
baseURL: https://centurio.net
languageCode: en-us
title: Centurios Blog
theme: "stack"
enableGitInfo: true

frontmatter:
  lastmod: ['lastmod', ':git', 'date', 'publishDate']

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 1

  disablePathToLower: false
permalinks:
  post: "/:year/:month/:day/:title/"

params:
  rssFullContent: true
  article:
    toc: true
    readingTime: true
  comments:
    enabled: false
  sidebar:
    subtitle: Macs, Linux, IoT and Photography
    avatar:
      enabled: true
      local: true
      src: img/avatar.png
  widgets:
    enabled:
      - search
      - categories
      - archives
      - tag-cloud
    archives:
      limit: 5
    tagCloud:
      limit: 10
    categoriesCloud:
      limit: 20

menu:
    social:
        - identifier: github
          name: GitHub
          url: 'https://github.com/rudelm/'
          params:
            icon: github
            newTab: true
        
        - identifier: mastodon
          name: Mastodon
          url: 'https://infosec.exchange/@rudelm'
          params:
            icon: mastodon
            newTab: true

        - identifier: twitter
          name: Twitter
          url: 'https://twitter.com/rudelm'
          params:
            icon: twitter
            newTab: true
```

### Hugo version

v0.110.0+extended darwin/arm64

### Theme version

3.16.0

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

109.0.5414.119 macOS Ventura 13.2

### Link to the page with bug

https://centurio.net/page/search/?keyword=mqtt
