### ISSUE TITLE
[Bug]: According repo hugo-theme-stack-starter

### ISSUE THREAD

**Issue by beTaller99** [CaiJimmy/hugo-theme-stack#820]
### What happened?

# 如何解决构建失败的问题
**How to resolve build failures?**
according the ‘To get started’ steps in repo  hugo-theme-stack-starter：
after creating codespace associated with the my repo which is created by the first step，
workflow occur a error ：
![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/82265836/cd4761f8-5b61-4428-8f2c-b5bf053cf6c5)

the workflow file is below：
```
name: Deploy to Github Pages

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Cache Hugo resources
              uses: actions/cache@v2
              env:
                  cache-name: cache-hugo-resources
              with:
                  path: resources
                  key: ${{ env.cache-name }}

            - uses: actions/setup-go@v2
              with:
                  go-version: "^1.17.0"
            - run: go version

            - name: Cache Go Modules
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Build
              run: hugo --minify --gc

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: public
                  clean: true
                  single-commit: true
```

### Hugo version

latest

### Theme version

latest

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by aster-hu** [comment]
I had the same problem and it seems like an issue caused by Hugo's [latest release v0.112.x](https://github.com/gohugoio/hugo/releases).

Changing the Hugo version back to v0.111.3 solved the issue for me.


```yml
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: 0.111.3
                  extended: true
```
