### ISSUE TITLE
[Bug]:  Code box not rendering properly

### ISSUE THREAD

**Issue by IHKYoung** [CaiJimmy/hugo-theme-stack#863]
### What happened?

The code box portion is not being rendered properly, as shown below:

<img width="824" alt="image" src="https://github.com/CaiJimmy/hugo-theme-stack/assets/100593787/5a547211-8e46-4026-85b5-b0117daf217f">

### Hugo version

0.117, 0.99.1 were all tested, and the effect suppression

### Theme version

3.18.0

### What browsers are you seeing the problem on?

Chrome, Safari

### Link to the page with bug

https://ahaknow.com

**Comment by CaiJimmy** [comment]
Try https://github.com/CaiJimmy/hugo-theme-stack/issues/695#issuecomment-1267181213

If it doesn't work, provide a minimal reproducible example using the starter template: https://github.com/CaiJimmy/hugo-theme-stack-starter. Otherwise, it is hard for me to figure out the problem since this problem does not appear on the test site (https://dev.stack.jimmycai.com/p/markdown-syntax-guide/)

**Comment by IHKYoung** [comment]
It looks like you're the one who didn't understand what I meant, the code box isn't being rendered properly, there's no serial number, there's no rendered highlighting, even if it's set properly
```yaml
markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        hl_Lines: ""
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
```


> Try [#695 (comment)](https://github.com/CaiJimmy/hugo-theme-stack/issues/695#issuecomment-1267181213)
> 
> If it doesn't work, provide a minimal reproducible example using the starter template: https://github.com/CaiJimmy/hugo-theme-stack-starter. Otherwise, it is hard for me to figure out the problem since this problem does not appear on the test site (https://dev.stack.jimmycai.com/p/markdown-syntax-guide/)
