### ISSUE TITLE
favicon不显示

### ISSUE THREAD

**Issue by OnqiauJliu** [CaiJimmy/hugo-theme-stack#865]
### What happened?

环境： hugomods/hugo:exts 
hugo版本: v0.117

我通过hugo mod 安装的本主题， 在设置 avatar 和 favicon 时使用的是同一张图片，  但 favicon 并不显示。具体的文件目录如下：
![{6ED90CD4-638E-41a1-84B0-09E752BF2842}](https://github.com/CaiJimmy/hugo-theme-stack/assets/60482496/b3af8a3e-1bf6-4fa2-b7f8-11f97eb4520e)

`F0AB8C6E-5A6C-44F2-B835-8245BB435E7A.JPG` 为原本图片文件名， 放在 assets/img 目录下是为了设置 avatar， 放在 static/img 目录下是为了设置 favicon， public/ 和 resource/ 目录均通过 `hugo`命令生成。 hugo.yaml 部分配置文件如下：

```yaml
...

params:
  featuredImageField: image
  favicon: /img/F0AB8C6E-5A6C-44F2-B835-8245BB435E7A.JPG

  sidebar:
    avatar:
      enabled: true
      local: true
      src: img/F0AB8C6E-5A6C-44F2-B835-8245BB435E7A.JPG

...

```

在上述情况下 favicon 无法正常显示， 将 favicon 改为如下路径才能正常运行：

```yaml
params:
  favicon: /img/F0AB8C6E-5A6C-44F2-B835-8245BB435E7A_hu2ef8ae4eab63e0e8e5615a43e17c40bf_23416_300x0_resize_q75_box.JPG
```
但 `F0AB8C6E-5A6C-44F2-B835-8245BB435E7A_hu2ef8ae4eab63e0e8e5615a43e17c40bf_23416_300x0_resize_q75_box.JPG` 图片是由原本图片 `F0AB8C6E-5A6C-44F2-B835-8245BB435E7A.JPG` 重命名而来， 不清楚为什么要重命名， 以及 favicon 正常路径应该是用的原本文件名。

对public/ 和 resource/ 文件夹删除后重新生成会得到相同的重命名图片。

### Hugo version

hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended

### Theme version

3.18.0

### What browsers are you seeing the problem on?

Chrome

### Link to Minimal Reproducible Example

none
