### ISSUE TITLE
the toc can not show Katex

### ISSUE THREAD

**Issue by 3000ye** [CaiJimmy/hugo-theme-stack#882]
## the toc can not show Katex

![toc](https://github.com/CaiJimmy/hugo-theme-stack/assets/87135443/5f8fe1c2-bfd5-44eb-85d5-92aad6ab45a3)

## more info
I use the quick-starter build the site, this is my `params.toml`:

```toml
# 数学支持 KaTex
[article]
math = true
readingTime = true
toc = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"
```

this is my post/xx.md:

```md
---
title: Elegant LaTeX
description: How to elegantly use LaTeX to create
date: 2023-10-09T17:18:55+08:00
image: assets/latex.jpg
math: true
toc: true
categories:
    - Note tools
tags:
    - Latex
---
```

### Hugo version

0.119.0

### Theme version

3.20.0

### What browsers are you seeing the problem on?

Microsoft Edge

### More information about the browser

macos

### Link to Minimal Reproducible Example

https://github.com/3000ye/3000yeBlog
